// Code generated by MockGen. DO NOT EDIT.
// Source: cdp.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockCDP is a mock of CDP interface.
type MockCDP struct {
	ctrl     *gomock.Controller
	recorder *MockCDPMockRecorder
}

// MockCDPMockRecorder is the mock recorder for MockCDP.
type MockCDPMockRecorder struct {
	mock *MockCDP
}

// NewMockCDP creates a new mock instance.
func NewMockCDP(ctrl *gomock.Controller) *MockCDP {
	mock := &MockCDP{ctrl: ctrl}
	mock.recorder = &MockCDPMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCDP) EXPECT() *MockCDPMockRecorder {
	return m.recorder
}

// Close mocks base method.
func (m *MockCDP) Close() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Close")
}

// Close indicates an expected call of Close.
func (mr *MockCDPMockRecorder) Close() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockCDP)(nil).Close))
}

// Init mocks base method.
func (m *MockCDP) Init(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Init", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// Init indicates an expected call of Init.
func (mr *MockCDPMockRecorder) Init(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Init", reflect.TypeOf((*MockCDP)(nil).Init), ctx)
}

// Initialized mocks base method.
func (m *MockCDP) Initialized() bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Initialized")
	ret0, _ := ret[0].(bool)
	return ret0
}

// Initialized indicates an expected call of Initialized.
func (mr *MockCDPMockRecorder) Initialized() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Initialized", reflect.TypeOf((*MockCDP)(nil).Initialized))
}

// NoLogSend mocks base method.
func (m *MockCDP) NoLogSend(method string, params map[string]interface{}) (interface{}, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NoLogSend", method, params)
	ret0, _ := ret[0].(interface{})
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// NoLogSend indicates an expected call of NoLogSend.
func (mr *MockCDPMockRecorder) NoLogSend(method, params interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NoLogSend", reflect.TypeOf((*MockCDP)(nil).NoLogSend), method, params)
}

// Send mocks base method.
func (m *MockCDP) Send(method string, params map[string]interface{}) (interface{}, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Send", method, params)
	ret0, _ := ret[0].(interface{})
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Send indicates an expected call of Send.
func (mr *MockCDPMockRecorder) Send(method, params interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Send", reflect.TypeOf((*MockCDP)(nil).Send), method, params)
}
