// Code generated by MockGen. DO NOT EDIT.
// Source: command.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"

	command "github.com/feral-file/ffos-user/components/feral-controld/command"
	status "github.com/feral-file/ffos-user/components/feral-controld/status"
)

// MockCommandHandler is a mock of CommandHandler interface.
type MockCommandHandler struct {
	ctrl     *gomock.Controller
	recorder *MockCommandHandlerMockRecorder
}

// MockCommandHandlerMockRecorder is the mock recorder for MockCommandHandler.
type MockCommandHandlerMockRecorder struct {
	mock *MockCommandHandler
}

// NewMockCommandHandler creates a new mock instance.
func NewMockCommandHandler(ctrl *gomock.Controller) *MockCommandHandler {
	mock := &MockCommandHandler{ctrl: ctrl}
	mock.recorder = &MockCommandHandlerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCommandHandler) EXPECT() *MockCommandHandlerMockRecorder {
	return m.recorder
}

// Execute mocks base method.
func (m *MockCommandHandler) Execute(ctx context.Context, cmd command.Command) (interface{}, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Execute", ctx, cmd)
	ret0, _ := ret[0].(interface{})
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Execute indicates an expected call of Execute.
func (mr *MockCommandHandlerMockRecorder) Execute(ctx, cmd interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Execute", reflect.TypeOf((*MockCommandHandler)(nil).Execute), ctx, cmd)
}

// SaveLastSysMetrics mocks base method.
func (m *MockCommandHandler) SaveLastSysMetrics(metrics []byte) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SaveLastSysMetrics", metrics)
}

// SaveLastSysMetrics indicates an expected call of SaveLastSysMetrics.
func (mr *MockCommandHandlerMockRecorder) SaveLastSysMetrics(metrics interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveLastSysMetrics", reflect.TypeOf((*MockCommandHandler)(nil).SaveLastSysMetrics), metrics)
}

// SetStatusPoller mocks base method.
func (m *MockCommandHandler) SetStatusPoller(statusPoller status.Poller) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetStatusPoller", statusPoller)
}

// SetStatusPoller indicates an expected call of SetStatusPoller.
func (mr *MockCommandHandlerMockRecorder) SetStatusPoller(statusPoller interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetStatusPoller", reflect.TypeOf((*MockCommandHandler)(nil).SetStatusPoller), statusPoller)
}
