// Code generated by MockGen. DO NOT EDIT.
// Source: ddc.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	json "encoding/json"
	reflect "reflect"

	ddc "github.com/feral-file/ffos-user/components/feral-controld/ddc"
	gomock "github.com/golang/mock/gomock"
)

// MockPanelDDC is a mock of PanelDDC interface
type MockPanelDDC struct {
	ctrl     *gomock.Controller
	recorder *MockPanelDDCMockRecorder
}

// MockPanelDDCMockRecorder is the mock recorder for MockPanelDDC
type MockPanelDDCMockRecorder struct {
	mock *MockPanelDDC
}

// NewMockPanelDDC creates a new mock instance
func NewMockPanelDDC(ctrl *gomock.Controller) *MockPanelDDC {
	mock := &MockPanelDDC{ctrl: ctrl}
	mock.recorder = &MockPanelDDCMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockPanelDDC) EXPECT() *MockPanelDDCMockRecorder {
	return m.recorder
}

// ApplyControl mocks base method
func (m *MockPanelDDC) ApplyControl(ctx context.Context, action ddc.DdcPanelAction, value json.RawMessage) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ApplyControl", ctx, action, value)
	ret0, _ := ret[0].(error)
	return ret0
}

// ApplyControl indicates an expected call of ApplyControl
func (mr *MockPanelDDCMockRecorder) ApplyControl(ctx, action, value interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ApplyControl", reflect.TypeOf((*MockPanelDDC)(nil).ApplyControl), ctx, action, value)
}

// CollectStatus mocks base method
func (m *MockPanelDDC) CollectStatus(ctx context.Context) (*ddc.DdcPanelStatus, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CollectStatus", ctx)
	ret0, _ := ret[0].(*ddc.DdcPanelStatus)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CollectStatus indicates an expected call of CollectStatus
func (mr *MockPanelDDCMockRecorder) CollectStatus(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CollectStatus", reflect.TypeOf((*MockPanelDDC)(nil).CollectStatus), ctx)
}
