// Code generated by MockGen. DO NOT EDIT.
// Source: device_status.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	status "github.com/feral-file/ffos-user/components/feral-controld/status"
	gomock "github.com/golang/mock/gomock"
)

// MockDeviceStatus is a mock of DeviceStatus interface.
type MockDeviceStatus struct {
	ctrl     *gomock.Controller
	recorder *MockDeviceStatusMockRecorder
}

// MockDeviceStatusMockRecorder is the mock recorder for MockDeviceStatus.
type MockDeviceStatusMockRecorder struct {
	mock *MockDeviceStatus
}

// NewMockDeviceStatus creates a new mock instance.
func NewMockDeviceStatus(ctrl *gomock.Controller) *MockDeviceStatus {
	mock := &MockDeviceStatus{ctrl: ctrl}
	mock.recorder = &MockDeviceStatusMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDeviceStatus) EXPECT() *MockDeviceStatusMockRecorder {
	return m.recorder
}

// GetStatus mocks base method.
func (m *MockDeviceStatus) GetStatus(ctx context.Context) (*status.DeviceStatusResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetStatus", ctx)
	ret0, _ := ret[0].(*status.DeviceStatusResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetStatus indicates an expected call of GetStatus.
func (mr *MockDeviceStatusMockRecorder) GetStatus(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetStatus", reflect.TypeOf((*MockDeviceStatus)(nil).GetStatus), ctx)
}
