// Code generated by MockGen. DO NOT EDIT.
// Source: dp1.go
//
// Generated by this command:
//
//	mockgen -source=dp1.go -destination=../mocks/dp1.go -package=mocks -mock_names=DP1=MockDP1
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"

	dp1 "github.com/feral-file/ffos-user/components/feral-controld/dp1"
)

// MockDP1 is a mock of DP1 interface.
type MockDP1 struct {
	ctrl     *gomock.Controller
	recorder *MockDP1MockRecorder
	isgomock struct{}
}

// MockDP1MockRecorder is the mock recorder for MockDP1.
type MockDP1MockRecorder struct {
	mock *MockDP1
}

// NewMockDP1 creates a new mock instance.
func NewMockDP1(ctrl *gomock.Controller) *MockDP1 {
	mock := &MockDP1{ctrl: ctrl}
	mock.recorder = &MockDP1MockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDP1) EXPECT() *MockDP1MockRecorder {
	return m.recorder
}

// ProcessDynamicPlaylist mocks base method.
func (m *MockDP1) ProcessDynamicPlaylist(ctx context.Context, playlist dp1.Playlist, minimal bool) (*dp1.Playlist, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ProcessDynamicPlaylist", ctx, playlist, minimal)
	ret0, _ := ret[0].(*dp1.Playlist)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ProcessDynamicPlaylist indicates an expected call of ProcessDynamicPlaylist.
func (mr *MockDP1MockRecorder) ProcessDynamicPlaylist(ctx, playlist, minimal any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ProcessDynamicPlaylist", reflect.TypeOf((*MockDP1)(nil).ProcessDynamicPlaylist), ctx, playlist, minimal)
}

// ProcessPlaylistURL mocks base method.
func (m *MockDP1) ProcessPlaylistURL(ctx context.Context, url string, minimal bool) (*dp1.Playlist, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ProcessPlaylistURL", ctx, url, minimal)
	ret0, _ := ret[0].(*dp1.Playlist)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ProcessPlaylistURL indicates an expected call of ProcessPlaylistURL.
func (mr *MockDP1MockRecorder) ProcessPlaylistURL(ctx, url, minimal any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ProcessPlaylistURL", reflect.TypeOf((*MockDP1)(nil).ProcessPlaylistURL), ctx, url, minimal)
}

// ProcessPlaylistURLConditional mocks base method.
func (m *MockDP1) ProcessPlaylistURLConditional(ctx context.Context, url string, minimal bool, ifNoneMatch string) (*dp1.PlaylistURLResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ProcessPlaylistURLConditional", ctx, url, minimal, ifNoneMatch)
	ret0, _ := ret[0].(*dp1.PlaylistURLResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ProcessPlaylistURLConditional indicates an expected call of ProcessPlaylistURLConditional.
func (mr *MockDP1MockRecorder) ProcessPlaylistURLConditional(ctx, url, minimal, ifNoneMatch any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ProcessPlaylistURLConditional", reflect.TypeOf((*MockDP1)(nil).ProcessPlaylistURLConditional), ctx, url, minimal, ifNoneMatch)
}
