// Code generated by MockGen. DO NOT EDIT.
// Source: executor.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	commands "github.com/feral-file/ffos-user/components/feral-controld/commands"
	setupui "github.com/feral-file/ffos-user/components/feral-controld/setupui"
	gomock "github.com/golang/mock/gomock"
)

// MockExecutor is a mock of Executor interface.
type MockExecutor struct {
	ctrl     *gomock.Controller
	recorder *MockExecutorMockRecorder
}

// MockExecutorMockRecorder is the mock recorder for MockExecutor.
type MockExecutorMockRecorder struct {
	mock *MockExecutor
}

// NewMockExecutor creates a new mock instance.
func NewMockExecutor(ctrl *gomock.Controller) *MockExecutor {
	mock := &MockExecutor{ctrl: ctrl}
	mock.recorder = &MockExecutorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockExecutor) EXPECT() *MockExecutorMockRecorder {
	return m.recorder
}

// Execute mocks base method.
func (m *MockExecutor) Execute(ctx context.Context, cmd commands.Command) (interface{}, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Execute", ctx, cmd)
	ret0, _ := ret[0].(interface{})
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Execute indicates an expected call of Execute.
func (mr *MockExecutorMockRecorder) Execute(ctx, cmd interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Execute", reflect.TypeOf((*MockExecutor)(nil).Execute), ctx, cmd)
}

// SaveLastSysMetrics mocks base method.
func (m *MockExecutor) SaveLastSysMetrics(metrics []byte) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SaveLastSysMetrics", metrics)
}

// SaveLastSysMetrics indicates an expected call of SaveLastSysMetrics.
func (mr *MockExecutorMockRecorder) SaveLastSysMetrics(metrics interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveLastSysMetrics", reflect.TypeOf((*MockExecutor)(nil).SaveLastSysMetrics), metrics)
}

// SetDeviceNameObserver mocks base method.
func (m *MockExecutor) SetDeviceNameObserver(observer func(string)) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetDeviceNameObserver", observer)
}

// SetDeviceNameObserver indicates an expected call of SetDeviceNameObserver.
func (mr *MockExecutorMockRecorder) SetDeviceNameObserver(observer interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetDeviceNameObserver", reflect.TypeOf((*MockExecutor)(nil).SetDeviceNameObserver), observer)
}

// SetClaimObserver mocks base method.
func (m *MockExecutor) SetClaimObserver(observer func(bool)) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetClaimObserver", observer)
}

// SetClaimObserver indicates an expected call of SetClaimObserver.
func (mr *MockExecutorMockRecorder) SetClaimObserver(observer interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetClaimObserver", reflect.TypeOf((*MockExecutor)(nil).SetClaimObserver), observer)
}

// SetSetupUI mocks base method.
func (m *MockExecutor) SetSetupUI(ui *setupui.Service) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetSetupUI", ui)
}

// ResetStaged mocks base method.
func (m *MockExecutor) ResetStaged() bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ResetStaged")
	ret0, _ := ret[0].(bool)
	return ret0
}

// ResetStaged indicates an expected call of ResetStaged.
func (mr *MockExecutorMockRecorder) ResetStaged() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ResetStaged", reflect.TypeOf((*MockExecutor)(nil).ResetStaged))
}

// SetSetupUI indicates an expected call of SetSetupUI.
func (mr *MockExecutorMockRecorder) SetSetupUI(ui interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetSetupUI", reflect.TypeOf((*MockExecutor)(nil).SetSetupUI), ui)
}
