// Code generated by MockGen. DO NOT EDIT.
// Source: ff_indexer.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"

	ffindexer "github.com/feral-file/ffos-user/components/feral-controld/ff-indexer"
)

// MockFFIndexer is a mock of FFIndexer interface.
type MockFFIndexer struct {
	ctrl     *gomock.Controller
	recorder *MockFFIndexerMockRecorder
}

// MockFFIndexerMockRecorder is the mock recorder for MockFFIndexer.
type MockFFIndexerMockRecorder struct {
	mock *MockFFIndexer
}

// NewMockFFIndexer creates a new mock instance.
func NewMockFFIndexer(ctrl *gomock.Controller) *MockFFIndexer {
	mock := &MockFFIndexer{ctrl: ctrl}
	mock.recorder = &MockFFIndexerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockFFIndexer) EXPECT() *MockFFIndexerMockRecorder {
	return m.recorder
}

// QueryTokens mocks base method.
func (m *MockFFIndexer) QueryTokens(ctx context.Context, endpoint string, params map[string]string) ([]ffindexer.Token, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "QueryTokens", ctx, endpoint, params)
	ret0, _ := ret[0].([]ffindexer.Token)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// QueryTokens indicates an expected call of QueryTokens.
func (mr *MockFFIndexerMockRecorder) QueryTokens(ctx, endpoint, params interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "QueryTokens", reflect.TypeOf((*MockFFIndexer)(nil).QueryTokens), ctx, endpoint, params)
}
