// Code generated by MockGen. DO NOT EDIT.
// Source: logger/logger.go

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"
	time "time"

	logger "github.com/feral-file/ffos-user/components/feral-controld/logger"
	gomock "github.com/golang/mock/gomock"
	zap "go.uber.org/zap"
)

// MockLoggerManager is a mock of LoggerManager interface.
type MockLoggerManager struct {
	ctrl     *gomock.Controller
	recorder *MockLoggerManagerMockRecorder
}

// MockLoggerManagerMockRecorder is the mock recorder for MockLoggerManager.
type MockLoggerManagerMockRecorder struct {
	mock *MockLoggerManager
}

// NewMockLoggerManager creates a new mock instance.
func NewMockLoggerManager(ctrl *gomock.Controller) *MockLoggerManager {
	mock := &MockLoggerManager{ctrl: ctrl}
	mock.recorder = &MockLoggerManagerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockLoggerManager) EXPECT() *MockLoggerManagerMockRecorder {
	return m.recorder
}

// AddSentry mocks base method.
func (m *MockLoggerManager) AddSentry(logger *zap.Logger, config logger.SentryConfig) (*zap.Logger, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddSentry", logger, config)
	ret0, _ := ret[0].(*zap.Logger)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AddSentry indicates an expected call of AddSentry.
func (mr *MockLoggerManagerMockRecorder) AddSentry(logger, config interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddSentry", reflect.TypeOf((*MockLoggerManager)(nil).AddSentry), logger, config)
}

// FlushSentry mocks base method.
func (m *MockLoggerManager) FlushSentry(timeout time.Duration) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "FlushSentry", timeout)
}

// FlushSentry indicates an expected call of FlushSentry.
func (mr *MockLoggerManagerMockRecorder) FlushSentry(timeout interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FlushSentry", reflect.TypeOf((*MockLoggerManager)(nil).FlushSentry), timeout)
}

// New mocks base method.
func (m *MockLoggerManager) New(debug bool) (*zap.Logger, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "New", debug)
	ret0, _ := ret[0].(*zap.Logger)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// New indicates an expected call of New.
func (mr *MockLoggerManagerMockRecorder) New(debug interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "New", reflect.TypeOf((*MockLoggerManager)(nil).New), debug)
}

// SetGlobalTopicID mocks base method.
func (m *MockLoggerManager) SetGlobalTopicID(topicID string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetGlobalTopicID", topicID)
}

// SetGlobalTopicID indicates an expected call of SetGlobalTopicID.
func (mr *MockLoggerManagerMockRecorder) SetGlobalTopicID(topicID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetGlobalTopicID", reflect.TypeOf((*MockLoggerManager)(nil).SetGlobalTopicID), topicID)
}
