// Code generated by MockGen. DO NOT EDIT.
// Source: math.go

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockMath is a mock of Math interface.
type MockMath struct {
	ctrl     *gomock.Controller
	recorder *MockMathMockRecorder
}

// MockMathMockRecorder is the mock recorder for MockMath.
type MockMathMockRecorder struct {
	mock *MockMath
}

// NewMockMath creates a new mock instance.
func NewMockMath(ctrl *gomock.Controller) *MockMath {
	mock := &MockMath{ctrl: ctrl}
	mock.recorder = &MockMathMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMath) EXPECT() *MockMathMockRecorder {
	return m.recorder
}

// Max mocks base method.
func (m *MockMath) Max(x, y float64) float64 {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Max", x, y)
	ret0, _ := ret[0].(float64)
	return ret0
}

// Max indicates an expected call of Max.
func (mr *MockMathMockRecorder) Max(x, y interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Max", reflect.TypeOf((*MockMath)(nil).Max), x, y)
}

// Min mocks base method.
func (m *MockMath) Min(x, y float64) float64 {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Min", x, y)
	ret0, _ := ret[0].(float64)
	return ret0
}

// Min indicates an expected call of Min.
func (mr *MockMathMockRecorder) Min(x, y interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Min", reflect.TypeOf((*MockMath)(nil).Min), x, y)
}

// Sqrt mocks base method.
func (m *MockMath) Sqrt(x float64) float64 {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Sqrt", x)
	ret0, _ := ret[0].(float64)
	return ret0
}

// Sqrt indicates an expected call of Sqrt.
func (mr *MockMathMockRecorder) Sqrt(x interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Sqrt", reflect.TypeOf((*MockMath)(nil).Sqrt), x)
}
