// Code generated by MockGen. DO NOT EDIT.
// Source: advertiser.go

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"

	"github.com/feral-file/ffos-user/components/feral-controld/mdns"
)

// MockAdvertiser is a mock of Advertiser interface.
type MockAdvertiser struct {
	ctrl     *gomock.Controller
	recorder *MockAdvertiserMockRecorder
}

// MockAdvertiserMockRecorder is the mock recorder for MockAdvertiser.
type MockAdvertiserMockRecorder struct {
	mock *MockAdvertiser
}

// NewMockAdvertiser creates a new mock instance.
func NewMockAdvertiser(ctrl *gomock.Controller) *MockAdvertiser {
	mock := &MockAdvertiser{ctrl: ctrl}
	mock.recorder = &MockAdvertiserMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAdvertiser) EXPECT() *MockAdvertiserMockRecorder {
	return m.recorder
}

// Start mocks base method.
func (m *MockAdvertiser) Start(info mdns.DeviceInfo) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Start", info)
	ret0, _ := ret[0].(error)
	return ret0
}

// Start indicates an expected call of Start.
func (mr *MockAdvertiserMockRecorder) Start(info interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Start", reflect.TypeOf((*MockAdvertiser)(nil).Start), info)
}

// Stop mocks base method.
func (m *MockAdvertiser) Stop() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Stop")
}

// Stop indicates an expected call of Stop.
func (mr *MockAdvertiserMockRecorder) Stop() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Stop", reflect.TypeOf((*MockAdvertiser)(nil).Stop))
}
