// Code generated by MockGen. DO NOT EDIT.
// Source: mediator.go

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	mdns "github.com/feral-file/ffos-user/components/feral-controld/mdns"
	playersession "github.com/feral-file/ffos-user/components/feral-controld/playersession"
	status "github.com/feral-file/ffos-user/components/feral-controld/status"
	gomock "github.com/golang/mock/gomock"
)

// MockMediator is a mock of Mediator interface.
type MockMediator struct {
	ctrl     *gomock.Controller
	recorder *MockMediatorMockRecorder
}

// MockMediatorMockRecorder is the mock recorder for MockMediator.
type MockMediatorMockRecorder struct {
	mock *MockMediator
}

// NewMockMediator creates a new mock instance.
func NewMockMediator(ctrl *gomock.Controller) *MockMediator {
	mock := &MockMediator{ctrl: ctrl}
	mock.recorder = &MockMediatorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMediator) EXPECT() *MockMediatorMockRecorder {
	return m.recorder
}

// InitializeMDNS mocks base method.
func (m *MockMediator) InitializeMDNS(advertiser mdns.Advertiser, info mdns.DeviceInfo, link status.LinkState) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "InitializeMDNS", advertiser, info, link)
}

// InitializeMDNS indicates an expected call of InitializeMDNS.
func (mr *MockMediatorMockRecorder) InitializeMDNS(advertiser, info, link interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InitializeMDNS", reflect.TypeOf((*MockMediator)(nil).InitializeMDNS), advertiser, info, link)
}

// SetClaimed mocks base method.
func (m *MockMediator) SetClaimed(claimed bool) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetClaimed", claimed)
}

// SetClaimed indicates an expected call of SetClaimed.
func (mr *MockMediatorMockRecorder) SetClaimed(claimed interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetClaimed", reflect.TypeOf((*MockMediator)(nil).SetClaimed), claimed)
}

// SetConnectivityPushHook mocks base method.
func (m *MockMediator) SetConnectivityPushHook(fn func()) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetConnectivityPushHook", fn)
}

// SetConnectivityPushHook indicates an expected call of SetConnectivityPushHook.
func (mr *MockMediatorMockRecorder) SetConnectivityPushHook(fn interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetConnectivityPushHook", reflect.TypeOf((*MockMediator)(nil).SetConnectivityPushHook), fn)
}

// SetSession mocks base method.
func (m *MockMediator) SetSession(session *playersession.Session) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetSession", session)
}

// SetSession indicates an expected call of SetSession.
func (mr *MockMediatorMockRecorder) SetSession(session interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetSession", reflect.TypeOf((*MockMediator)(nil).SetSession), session)
}

// SetSysMetricsObserver mocks base method.
func (m *MockMediator) SetSysMetricsObserver(observer func([]byte)) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetSysMetricsObserver", observer)
}

// SetSysMetricsObserver indicates an expected call of SetSysMetricsObserver.
func (mr *MockMediatorMockRecorder) SetSysMetricsObserver(observer interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetSysMetricsObserver", reflect.TypeOf((*MockMediator)(nil).SetSysMetricsObserver), observer)
}

// SetTopicObserver mocks base method.
func (m *MockMediator) SetTopicObserver(observer func()) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetTopicObserver", observer)
}

// SetTopicObserver indicates an expected call of SetTopicObserver.
func (mr *MockMediatorMockRecorder) SetTopicObserver(observer interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetTopicObserver", reflect.TypeOf((*MockMediator)(nil).SetTopicObserver), observer)
}

// Start mocks base method.
func (m *MockMediator) Start() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Start")
}

// Start indicates an expected call of Start.
func (mr *MockMediatorMockRecorder) Start() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Start", reflect.TypeOf((*MockMediator)(nil).Start))
}

// Stop mocks base method.
func (m *MockMediator) Stop() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Stop")
}

// Stop indicates an expected call of Stop.
func (mr *MockMediatorMockRecorder) Stop() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Stop", reflect.TypeOf((*MockMediator)(nil).Stop))
}
