// Code generated by MockGen. DO NOT EDIT.
// Source: metric.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"

	dp1 "github.com/feral-file/ffos-user/components/feral-controld/dp1"
)

// MockMetricTracker is a mock of Tracker interface.
type MockMetricTracker struct {
	ctrl     *gomock.Controller
	recorder *MockMetricTrackerMockRecorder
}

// MockMetricTrackerMockRecorder is the mock recorder for MockMetricTracker.
type MockMetricTrackerMockRecorder struct {
	mock *MockMetricTracker
}

// NewMockMetricTracker creates a new mock instance.
func NewMockMetricTracker(ctrl *gomock.Controller) *MockMetricTracker {
	mock := &MockMetricTracker{ctrl: ctrl}
	mock.recorder = &MockMetricTrackerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMetricTracker) EXPECT() *MockMetricTrackerMockRecorder {
	return m.recorder
}

// Initialize mocks base method.
func (m *MockMetricTracker) Initialize() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Initialize")
	ret0, _ := ret[0].(error)
	return ret0
}

// Initialize indicates an expected call of Initialize.
func (mr *MockMetricTrackerMockRecorder) Initialize() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Initialize", reflect.TypeOf((*MockMetricTracker)(nil).Initialize))
}

// TrackPlaylistView mocks base method.
func (m *MockMetricTracker) TrackPlaylistView(ctx context.Context, playlist *dp1.Playlist, playlistURL string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TrackPlaylistView", ctx, playlist, playlistURL)
	ret0, _ := ret[0].(error)
	return ret0
}

// TrackPlaylistView indicates an expected call of TrackPlaylistView.
func (mr *MockMetricTrackerMockRecorder) TrackPlaylistView(ctx, playlist, playlistURL interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TrackPlaylistView", reflect.TypeOf((*MockMetricTracker)(nil).TrackPlaylistView), ctx, playlist, playlistURL)
}
