// Code generated by MockGen. DO NOT EDIT.
// Source: offlinecache/capture.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	playlist "github.com/display-protocol/dp1-go/playlist"
	offlinecache "github.com/feral-file/ffos-user/components/feral-controld/offlinecache"
	gomock "github.com/golang/mock/gomock"
)

// MockOfflineCacheCapturer is a mock of Capturer interface.
type MockOfflineCacheCapturer struct {
	ctrl     *gomock.Controller
	recorder *MockOfflineCacheCapturerMockRecorder
}

// MockOfflineCacheCapturerMockRecorder is the mock recorder for MockOfflineCacheCapturer.
type MockOfflineCacheCapturerMockRecorder struct {
	mock *MockOfflineCacheCapturer
}

// NewMockOfflineCacheCapturer creates a new mock instance.
func NewMockOfflineCacheCapturer(ctrl *gomock.Controller) *MockOfflineCacheCapturer {
	mock := &MockOfflineCacheCapturer{ctrl: ctrl}
	mock.recorder = &MockOfflineCacheCapturerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockOfflineCacheCapturer) EXPECT() *MockOfflineCacheCapturerMockRecorder {
	return m.recorder
}

// Capture mocks base method.
func (m *MockOfflineCacheCapturer) Capture(ctx context.Context, item playlist.PlaylistItem, captureWindowMs int) (*offlinecache.ItemRecord, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Capture", ctx, item, captureWindowMs)
	ret0, _ := ret[0].(*offlinecache.ItemRecord)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Capture indicates an expected call of Capture.
func (mr *MockOfflineCacheCapturerMockRecorder) Capture(ctx, item, captureWindowMs interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Capture", reflect.TypeOf((*MockOfflineCacheCapturer)(nil).Capture), ctx, item, captureWindowMs)
}

// Close mocks base method.
func (m *MockOfflineCacheCapturer) Close() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Close")
	ret0, _ := ret[0].(error)
	return ret0
}

// Close indicates an expected call of Close.
func (mr *MockOfflineCacheCapturerMockRecorder) Close() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockOfflineCacheCapturer)(nil).Close))
}
