// Code generated by MockGen. DO NOT EDIT.
// Source: kioskreplay.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockOfflineCacheKioskReplay is a mock of KioskReplay interface.
type MockOfflineCacheKioskReplay struct {
	ctrl     *gomock.Controller
	recorder *MockOfflineCacheKioskReplayMockRecorder
}

// MockOfflineCacheKioskReplayMockRecorder is the mock recorder for MockOfflineCacheKioskReplay.
type MockOfflineCacheKioskReplayMockRecorder struct {
	mock *MockOfflineCacheKioskReplay
}

// NewMockOfflineCacheKioskReplay creates a new mock instance.
func NewMockOfflineCacheKioskReplay(ctrl *gomock.Controller) *MockOfflineCacheKioskReplay {
	mock := &MockOfflineCacheKioskReplay{ctrl: ctrl}
	mock.recorder = &MockOfflineCacheKioskReplayMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockOfflineCacheKioskReplay) EXPECT() *MockOfflineCacheKioskReplayMockRecorder {
	return m.recorder
}

// AttachOnReconnect mocks base method.
func (m *MockOfflineCacheKioskReplay) AttachOnReconnect(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AttachOnReconnect", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// AttachOnReconnect indicates an expected call of AttachOnReconnect.
func (mr *MockOfflineCacheKioskReplayMockRecorder) AttachOnReconnect(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AttachOnReconnect", reflect.TypeOf((*MockOfflineCacheKioskReplay)(nil).AttachOnReconnect), ctx)
}

// SyncPlaylist mocks base method.
func (m *MockOfflineCacheKioskReplay) SyncPlaylist(ctx context.Context, itemIDs []string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SyncPlaylist", ctx, itemIDs)
	ret0, _ := ret[0].(error)
	return ret0
}

// SyncPlaylist indicates an expected call of SyncPlaylist.
func (mr *MockOfflineCacheKioskReplayMockRecorder) SyncPlaylist(ctx, itemIDs interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SyncPlaylist", reflect.TypeOf((*MockOfflineCacheKioskReplay)(nil).SyncPlaylist), ctx, itemIDs)
}

// LockPlayback mocks base method.
func (m *MockOfflineCacheKioskReplay) LockPlayback() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "LockPlayback")
}

// LockPlayback indicates an expected call of LockPlayback.
func (mr *MockOfflineCacheKioskReplayMockRecorder) LockPlayback() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LockPlayback", reflect.TypeOf((*MockOfflineCacheKioskReplay)(nil).LockPlayback))
}

// UnlockPlayback mocks base method.
func (m *MockOfflineCacheKioskReplay) UnlockPlayback() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "UnlockPlayback")
}

// UnlockPlayback indicates an expected call of UnlockPlayback.
func (mr *MockOfflineCacheKioskReplayMockRecorder) UnlockPlayback() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UnlockPlayback", reflect.TypeOf((*MockOfflineCacheKioskReplay)(nil).UnlockPlayback))
}

// PlaybackGeneration mocks base method.
func (m *MockOfflineCacheKioskReplay) PlaybackGeneration() uint64 {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PlaybackGeneration")
	ret0, _ := ret[0].(uint64)
	return ret0
}

// PlaybackGeneration indicates an expected call of PlaybackGeneration.
func (mr *MockOfflineCacheKioskReplayMockRecorder) PlaybackGeneration() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PlaybackGeneration", reflect.TypeOf((*MockOfflineCacheKioskReplay)(nil).PlaybackGeneration))
}

// MarkPlaybackChanged mocks base method.
func (m *MockOfflineCacheKioskReplay) MarkPlaybackChanged() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "MarkPlaybackChanged")
}

// MarkPlaybackChanged indicates an expected call of MarkPlaybackChanged.
func (mr *MockOfflineCacheKioskReplayMockRecorder) MarkPlaybackChanged() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MarkPlaybackChanged", reflect.TypeOf((*MockOfflineCacheKioskReplay)(nil).MarkPlaybackChanged))
}
