// Code generated by MockGen. DO NOT EDIT.
// Source: cdpsession.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	json "encoding/json"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockCDPSession is a mock of CDPSession interface.
type MockCDPSession struct {
	ctrl     *gomock.Controller
	recorder *MockCDPSessionMockRecorder
}

// MockCDPSessionMockRecorder is the mock recorder for MockCDPSession.
type MockCDPSessionMockRecorder struct {
	mock *MockCDPSession
}

// NewMockCDPSession creates a new mock instance.
func NewMockCDPSession(ctrl *gomock.Controller) *MockCDPSession {
	mock := &MockCDPSession{ctrl: ctrl}
	mock.recorder = &MockCDPSessionMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCDPSession) EXPECT() *MockCDPSessionMockRecorder {
	return m.recorder
}

// Close mocks base method.
func (m *MockCDPSession) Close() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Close")
	ret0, _ := ret[0].(error)
	return ret0
}

// Close indicates an expected call of Close.
func (mr *MockCDPSessionMockRecorder) Close() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockCDPSession)(nil).Close))
}

// On mocks base method.
func (m *MockCDPSession) On(method string, handler func(json.RawMessage)) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "On", method, handler)
}

// On indicates an expected call of On.
func (mr *MockCDPSessionMockRecorder) On(method, handler interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "On", reflect.TypeOf((*MockCDPSession)(nil).On), method, handler)
}

// Send mocks base method.
func (m *MockCDPSession) Send(ctx context.Context, method string, params map[string]interface{}) (json.RawMessage, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Send", ctx, method, params)
	ret0, _ := ret[0].(json.RawMessage)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Send indicates an expected call of Send.
func (mr *MockCDPSessionMockRecorder) Send(ctx, method, params interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Send", reflect.TypeOf((*MockCDPSession)(nil).Send), ctx, method, params)
}
