// Code generated by MockGen. DO NOT EDIT.
// Source: offlinecache/replay.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	offlinecache "github.com/feral-file/ffos-user/components/feral-controld/offlinecache"
	gomock "github.com/golang/mock/gomock"
)

// MockOfflineCacheReplayer is a mock of Replayer interface.
type MockOfflineCacheReplayer struct {
	ctrl     *gomock.Controller
	recorder *MockOfflineCacheReplayerMockRecorder
}

// MockOfflineCacheReplayerMockRecorder is the mock recorder for MockOfflineCacheReplayer.
type MockOfflineCacheReplayerMockRecorder struct {
	mock *MockOfflineCacheReplayer
}

// NewMockOfflineCacheReplayer creates a new mock instance.
func NewMockOfflineCacheReplayer(ctrl *gomock.Controller) *MockOfflineCacheReplayer {
	mock := &MockOfflineCacheReplayer{ctrl: ctrl}
	mock.recorder = &MockOfflineCacheReplayerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockOfflineCacheReplayer) EXPECT() *MockOfflineCacheReplayerMockRecorder {
	return m.recorder
}

// Attach mocks base method.
func (m *MockOfflineCacheReplayer) Attach(sessionID string, session offlinecache.CDPSession) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Attach", sessionID, session)
}

// Attach indicates an expected call of Attach.
func (mr *MockOfflineCacheReplayerMockRecorder) Attach(sessionID, session interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Attach", reflect.TypeOf((*MockOfflineCacheReplayer)(nil).Attach), sessionID, session)
}

// Detach mocks base method.
func (m *MockOfflineCacheReplayer) Detach(sessionID string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Detach", sessionID)
}

// Detach indicates an expected call of Detach.
func (mr *MockOfflineCacheReplayerMockRecorder) Detach(sessionID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Detach", reflect.TypeOf((*MockOfflineCacheReplayer)(nil).Detach), sessionID)
}

// Disable mocks base method.
func (m *MockOfflineCacheReplayer) Disable(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Disable", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// Disable indicates an expected call of Disable.
func (mr *MockOfflineCacheReplayerMockRecorder) Disable(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Disable", reflect.TypeOf((*MockOfflineCacheReplayer)(nil).Disable), ctx)
}

// EnableForItem mocks base method.
func (m *MockOfflineCacheReplayer) EnableForItem(ctx context.Context, itemID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "EnableForItem", ctx, itemID)
	ret0, _ := ret[0].(error)
	return ret0
}

// EnableForItem indicates an expected call of EnableForItem.
func (mr *MockOfflineCacheReplayerMockRecorder) EnableForItem(ctx, itemID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EnableForItem", reflect.TypeOf((*MockOfflineCacheReplayer)(nil).EnableForItem), ctx, itemID)
}

// EnableForPlaylist mocks base method.
func (m *MockOfflineCacheReplayer) EnableForPlaylist(ctx context.Context, itemIDs []string, mixed bool) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "EnableForPlaylist", ctx, itemIDs, mixed)
	ret0, _ := ret[0].(error)
	return ret0
}

// EnableForPlaylist indicates an expected call of EnableForPlaylist.
func (mr *MockOfflineCacheReplayerMockRecorder) EnableForPlaylist(ctx, itemIDs, mixed interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EnableForPlaylist", reflect.TypeOf((*MockOfflineCacheReplayer)(nil).EnableForPlaylist), ctx, itemIDs, mixed)
}
