// Code generated by MockGen. DO NOT EDIT.
// Source: service.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	json "encoding/json"
	reflect "reflect"

	playlist "github.com/display-protocol/dp1-go/playlist"
	offlinecache "github.com/feral-file/ffos-user/components/feral-controld/offlinecache"
	gomock "github.com/golang/mock/gomock"
)

// MockOfflineCacheProgressObserver is a mock of ProgressObserver interface.
type MockOfflineCacheProgressObserver struct {
	ctrl     *gomock.Controller
	recorder *MockOfflineCacheProgressObserverMockRecorder
}

// MockOfflineCacheProgressObserverMockRecorder is the mock recorder for MockOfflineCacheProgressObserver.
type MockOfflineCacheProgressObserverMockRecorder struct {
	mock *MockOfflineCacheProgressObserver
}

// NewMockOfflineCacheProgressObserver creates a new mock instance.
func NewMockOfflineCacheProgressObserver(ctrl *gomock.Controller) *MockOfflineCacheProgressObserver {
	mock := &MockOfflineCacheProgressObserver{ctrl: ctrl}
	mock.recorder = &MockOfflineCacheProgressObserverMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockOfflineCacheProgressObserver) EXPECT() *MockOfflineCacheProgressObserverMockRecorder {
	return m.recorder
}

// OnItemStateChanged mocks base method.
func (m *MockOfflineCacheProgressObserver) OnItemStateChanged(status offlinecache.ItemStatus) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "OnItemStateChanged", status)
}

// OnItemStateChanged indicates an expected call of OnItemStateChanged.
func (mr *MockOfflineCacheProgressObserverMockRecorder) OnItemStateChanged(status interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "OnItemStateChanged", reflect.TypeOf((*MockOfflineCacheProgressObserver)(nil).OnItemStateChanged), status)
}

// MockOfflineCacheService is a mock of Service interface.
type MockOfflineCacheService struct {
	ctrl     *gomock.Controller
	recorder *MockOfflineCacheServiceMockRecorder
}

// MockOfflineCacheServiceMockRecorder is the mock recorder for MockOfflineCacheService.
type MockOfflineCacheServiceMockRecorder struct {
	mock *MockOfflineCacheService
}

// NewMockOfflineCacheService creates a new mock instance.
func NewMockOfflineCacheService(ctrl *gomock.Controller) *MockOfflineCacheService {
	mock := &MockOfflineCacheService{ctrl: ctrl}
	mock.recorder = &MockOfflineCacheServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockOfflineCacheService) EXPECT() *MockOfflineCacheServiceMockRecorder {
	return m.recorder
}

// CachedPlaylistForURL mocks base method.
func (m *MockOfflineCacheService) CachedPlaylistForURL(sourceURL string) (json.RawMessage, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CachedPlaylistForURL", sourceURL)
	ret0, _ := ret[0].(json.RawMessage)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CachedPlaylistForURL indicates an expected call of CachedPlaylistForURL.
func (mr *MockOfflineCacheServiceMockRecorder) CachedPlaylistForURL(sourceURL interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CachedPlaylistForURL", reflect.TypeOf((*MockOfflineCacheService)(nil).CachedPlaylistForURL), sourceURL)
}

// ClearItem mocks base method.
func (m *MockOfflineCacheService) ClearItem(itemID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ClearItem", itemID)
	ret0, _ := ret[0].(error)
	return ret0
}

// ClearItem indicates an expected call of ClearItem.
func (mr *MockOfflineCacheServiceMockRecorder) ClearItem(itemID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ClearItem", reflect.TypeOf((*MockOfflineCacheService)(nil).ClearItem), itemID)
}

// ClearPlaylist mocks base method.
func (m *MockOfflineCacheService) ClearPlaylist(playlistID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ClearPlaylist", playlistID)
	ret0, _ := ret[0].(error)
	return ret0
}

// ClearPlaylist indicates an expected call of ClearPlaylist.
func (mr *MockOfflineCacheServiceMockRecorder) ClearPlaylist(playlistID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ClearPlaylist", reflect.TypeOf((*MockOfflineCacheService)(nil).ClearPlaylist), playlistID)
}

// DownloadItem mocks base method.
func (m *MockOfflineCacheService) DownloadItem(ctx context.Context, item playlist.PlaylistItem) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DownloadItem", ctx, item)
	ret0, _ := ret[0].(error)
	return ret0
}

// DownloadItem indicates an expected call of DownloadItem.
func (mr *MockOfflineCacheServiceMockRecorder) DownloadItem(ctx, item interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DownloadItem", reflect.TypeOf((*MockOfflineCacheService)(nil).DownloadItem), ctx, item)
}

// DownloadPlaylist mocks base method.
func (m *MockOfflineCacheService) DownloadPlaylist(ctx context.Context, playlistRaw json.RawMessage, sourceURL string) (int, int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DownloadPlaylist", ctx, playlistRaw, sourceURL)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(int)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// DownloadPlaylist indicates an expected call of DownloadPlaylist.
func (mr *MockOfflineCacheServiceMockRecorder) DownloadPlaylist(ctx, playlistRaw, sourceURL interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DownloadPlaylist", reflect.TypeOf((*MockOfflineCacheService)(nil).DownloadPlaylist), ctx, playlistRaw, sourceURL)
}

// Start mocks base method.
func (m *MockOfflineCacheService) Start(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Start", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// Start indicates an expected call of Start.
func (mr *MockOfflineCacheServiceMockRecorder) Start(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Start", reflect.TypeOf((*MockOfflineCacheService)(nil).Start), ctx)
}

// Status mocks base method.
func (m *MockOfflineCacheService) Status(itemIDs []string) (offlinecache.StatusSnapshot, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Status", itemIDs)
	ret0, _ := ret[0].(offlinecache.StatusSnapshot)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Status indicates an expected call of Status.
func (mr *MockOfflineCacheServiceMockRecorder) Status(itemIDs interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Status", reflect.TypeOf((*MockOfflineCacheService)(nil).Status), itemIDs)
}

// Stop mocks base method.
func (m *MockOfflineCacheService) Stop() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Stop")
}

// Stop indicates an expected call of Stop.
func (mr *MockOfflineCacheServiceMockRecorder) Stop() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Stop", reflect.TypeOf((*MockOfflineCacheService)(nil).Stop))
}
