// Code generated by MockGen. DO NOT EDIT.
// Source: probe.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	offlinecache "github.com/feral-file/ffos-user/components/feral-controld/offlinecache"
	gomock "github.com/golang/mock/gomock"
)

// MockSourceProber is a mock of SourceProber interface.
type MockSourceProber struct {
	ctrl     *gomock.Controller
	recorder *MockSourceProberMockRecorder
}

// MockSourceProberMockRecorder is the mock recorder for MockSourceProber.
type MockSourceProberMockRecorder struct {
	mock *MockSourceProber
}

// NewMockSourceProber creates a new mock instance.
func NewMockSourceProber(ctrl *gomock.Controller) *MockSourceProber {
	mock := &MockSourceProber{ctrl: ctrl}
	mock.recorder = &MockSourceProberMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSourceProber) EXPECT() *MockSourceProberMockRecorder {
	return m.recorder
}

// ProbeSources mocks base method.
func (m *MockSourceProber) ProbeSources(ctx context.Context, sources []string) []offlinecache.SourceProbeResult {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ProbeSources", ctx, sources)
	ret0, _ := ret[0].([]offlinecache.SourceProbeResult)
	return ret0
}

// ProbeSources indicates an expected call of ProbeSources.
func (mr *MockSourceProberMockRecorder) ProbeSources(ctx, sources interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ProbeSources", reflect.TypeOf((*MockSourceProber)(nil).ProbeSources), ctx, sources)
}
