// Code generated by MockGen. DO NOT EDIT.
// Source: classify.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	offlinecache "github.com/feral-file/ffos-user/components/feral-controld/offlinecache"
	gomock "github.com/golang/mock/gomock"
)

// MockOfflineCacheClassifier is a mock of Classifier interface.
type MockOfflineCacheClassifier struct {
	ctrl     *gomock.Controller
	recorder *MockOfflineCacheClassifierMockRecorder
}

// MockOfflineCacheClassifierMockRecorder is the mock recorder for MockOfflineCacheClassifier.
type MockOfflineCacheClassifierMockRecorder struct {
	mock *MockOfflineCacheClassifier
}

// NewMockOfflineCacheClassifier creates a new mock instance.
func NewMockOfflineCacheClassifier(ctrl *gomock.Controller) *MockOfflineCacheClassifier {
	mock := &MockOfflineCacheClassifier{ctrl: ctrl}
	mock.recorder = &MockOfflineCacheClassifierMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockOfflineCacheClassifier) EXPECT() *MockOfflineCacheClassifierMockRecorder {
	return m.recorder
}

// Classify mocks base method.
func (m *MockOfflineCacheClassifier) Classify(ctx context.Context, url string) (offlinecache.MediaClass, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Classify", ctx, url)
	ret0, _ := ret[0].(offlinecache.MediaClass)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Classify indicates an expected call of Classify.
func (mr *MockOfflineCacheClassifierMockRecorder) Classify(ctx, url interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Classify", reflect.TypeOf((*MockOfflineCacheClassifier)(nil).Classify), ctx, url)
}
