// Code generated by MockGen. DO NOT EDIT.
// Source: store.go

// Package mocks is a generated GoMock package.
package mocks

import (
	json "encoding/json"
	io "io"
	reflect "reflect"

	offlinecache "github.com/feral-file/ffos-user/components/feral-controld/offlinecache"
	gomock "github.com/golang/mock/gomock"
)

// MockOfflineCacheStore is a mock of Store interface.
type MockOfflineCacheStore struct {
	ctrl     *gomock.Controller
	recorder *MockOfflineCacheStoreMockRecorder
}

// MockOfflineCacheStoreMockRecorder is the mock recorder for MockOfflineCacheStore.
type MockOfflineCacheStoreMockRecorder struct {
	mock *MockOfflineCacheStore
}

// NewMockOfflineCacheStore creates a new mock instance.
func NewMockOfflineCacheStore(ctrl *gomock.Controller) *MockOfflineCacheStore {
	mock := &MockOfflineCacheStore{ctrl: ctrl}
	mock.recorder = &MockOfflineCacheStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockOfflineCacheStore) EXPECT() *MockOfflineCacheStoreMockRecorder {
	return m.recorder
}

// BlobPath mocks base method.
func (m *MockOfflineCacheStore) BlobPath(sha256Hex string) string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BlobPath", sha256Hex)
	ret0, _ := ret[0].(string)
	return ret0
}

// BlobPath indicates an expected call of BlobPath.
func (mr *MockOfflineCacheStoreMockRecorder) BlobPath(sha256Hex interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BlobPath", reflect.TypeOf((*MockOfflineCacheStore)(nil).BlobPath), sha256Hex)
}

// BlobSize mocks base method.
func (m *MockOfflineCacheStore) BlobSize(sha256Hex string) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BlobSize", sha256Hex)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// BlobSize indicates an expected call of BlobSize.
func (mr *MockOfflineCacheStoreMockRecorder) BlobSize(sha256Hex interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BlobSize", reflect.TypeOf((*MockOfflineCacheStore)(nil).BlobSize), sha256Hex)
}

// DeleteItem mocks base method.
func (m *MockOfflineCacheStore) DeleteItem(itemID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteItem", itemID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteItem indicates an expected call of DeleteItem.
func (mr *MockOfflineCacheStoreMockRecorder) DeleteItem(itemID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteItem", reflect.TypeOf((*MockOfflineCacheStore)(nil).DeleteItem), itemID)
}

// DeletePlaylist mocks base method.
func (m *MockOfflineCacheStore) DeletePlaylist(playlistID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeletePlaylist", playlistID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeletePlaylist indicates an expected call of DeletePlaylist.
func (mr *MockOfflineCacheStoreMockRecorder) DeletePlaylist(playlistID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeletePlaylist", reflect.TypeOf((*MockOfflineCacheStore)(nil).DeletePlaylist), playlistID)
}

// DiskUsage mocks base method.
func (m *MockOfflineCacheStore) DiskUsage() (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DiskUsage")
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DiskUsage indicates an expected call of DiskUsage.
func (mr *MockOfflineCacheStoreMockRecorder) DiskUsage() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DiskUsage", reflect.TypeOf((*MockOfflineCacheStore)(nil).DiskUsage))
}

// GC mocks base method.
func (m *MockOfflineCacheStore) GC() (int, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GC")
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GC indicates an expected call of GC.
func (mr *MockOfflineCacheStoreMockRecorder) GC() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GC", reflect.TypeOf((*MockOfflineCacheStore)(nil).GC))
}

// ListItemIDs mocks base method.
func (m *MockOfflineCacheStore) ListItemIDs() ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListItemIDs")
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListItemIDs indicates an expected call of ListItemIDs.
func (mr *MockOfflineCacheStoreMockRecorder) ListItemIDs() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListItemIDs", reflect.TypeOf((*MockOfflineCacheStore)(nil).ListItemIDs))
}

// ListPlaylistIDs mocks base method.
func (m *MockOfflineCacheStore) ListPlaylistIDs() ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListPlaylistIDs")
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListPlaylistIDs indicates an expected call of ListPlaylistIDs.
func (mr *MockOfflineCacheStoreMockRecorder) ListPlaylistIDs() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListPlaylistIDs", reflect.TypeOf((*MockOfflineCacheStore)(nil).ListPlaylistIDs))
}

// LoadItem mocks base method.
func (m *MockOfflineCacheStore) LoadItem(itemID string) (*offlinecache.ItemRecord, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LoadItem", itemID)
	ret0, _ := ret[0].(*offlinecache.ItemRecord)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// LoadItem indicates an expected call of LoadItem.
func (mr *MockOfflineCacheStoreMockRecorder) LoadItem(itemID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LoadItem", reflect.TypeOf((*MockOfflineCacheStore)(nil).LoadItem), itemID)
}

// LoadPlaylist mocks base method.
func (m *MockOfflineCacheStore) LoadPlaylist(playlistID string) (json.RawMessage, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LoadPlaylist", playlistID)
	ret0, _ := ret[0].(json.RawMessage)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// LoadPlaylist indicates an expected call of LoadPlaylist.
func (mr *MockOfflineCacheStoreMockRecorder) LoadPlaylist(playlistID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LoadPlaylist", reflect.TypeOf((*MockOfflineCacheStore)(nil).LoadPlaylist), playlistID)
}

// LoadPlaylistIDForURL mocks base method.
func (m *MockOfflineCacheStore) LoadPlaylistIDForURL(sourceURL string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LoadPlaylistIDForURL", sourceURL)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// LoadPlaylistIDForURL indicates an expected call of LoadPlaylistIDForURL.
func (mr *MockOfflineCacheStoreMockRecorder) LoadPlaylistIDForURL(sourceURL interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LoadPlaylistIDForURL", reflect.TypeOf((*MockOfflineCacheStore)(nil).LoadPlaylistIDForURL), sourceURL)
}

// ReadBlob mocks base method.
func (m *MockOfflineCacheStore) ReadBlob(sha256Hex string) ([]byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReadBlob", sha256Hex)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ReadBlob indicates an expected call of ReadBlob.
func (mr *MockOfflineCacheStoreMockRecorder) ReadBlob(sha256Hex interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReadBlob", reflect.TypeOf((*MockOfflineCacheStore)(nil).ReadBlob), sha256Hex)
}

// RootDir mocks base method.
func (m *MockOfflineCacheStore) RootDir() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RootDir")
	ret0, _ := ret[0].(string)
	return ret0
}

// RootDir indicates an expected call of RootDir.
func (mr *MockOfflineCacheStoreMockRecorder) RootDir() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RootDir", reflect.TypeOf((*MockOfflineCacheStore)(nil).RootDir))
}

// SaveItem mocks base method.
func (m *MockOfflineCacheStore) SaveItem(rec *offlinecache.ItemRecord) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveItem", rec)
	ret0, _ := ret[0].(error)
	return ret0
}

// SaveItem indicates an expected call of SaveItem.
func (mr *MockOfflineCacheStoreMockRecorder) SaveItem(rec interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveItem", reflect.TypeOf((*MockOfflineCacheStore)(nil).SaveItem), rec)
}

// SavePlaylist mocks base method.
func (m *MockOfflineCacheStore) SavePlaylist(playlistID string, raw json.RawMessage) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SavePlaylist", playlistID, raw)
	ret0, _ := ret[0].(error)
	return ret0
}

// SavePlaylist indicates an expected call of SavePlaylist.
func (mr *MockOfflineCacheStoreMockRecorder) SavePlaylist(playlistID, raw interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SavePlaylist", reflect.TypeOf((*MockOfflineCacheStore)(nil).SavePlaylist), playlistID, raw)
}

// SavePlaylistURLIndex mocks base method.
func (m *MockOfflineCacheStore) SavePlaylistURLIndex(sourceURL, playlistID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SavePlaylistURLIndex", sourceURL, playlistID)
	ret0, _ := ret[0].(error)
	return ret0
}

// SavePlaylistURLIndex indicates an expected call of SavePlaylistURLIndex.
func (mr *MockOfflineCacheStoreMockRecorder) SavePlaylistURLIndex(sourceURL, playlistID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SavePlaylistURLIndex", reflect.TypeOf((*MockOfflineCacheStore)(nil).SavePlaylistURLIndex), sourceURL, playlistID)
}

// SweepIncompleteBlobs mocks base method.
func (m *MockOfflineCacheStore) SweepIncompleteBlobs() (int, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SweepIncompleteBlobs")
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// SweepIncompleteBlobs indicates an expected call of SweepIncompleteBlobs.
func (mr *MockOfflineCacheStoreMockRecorder) SweepIncompleteBlobs() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SweepIncompleteBlobs", reflect.TypeOf((*MockOfflineCacheStore)(nil).SweepIncompleteBlobs))
}

// WriteBlob mocks base method.
func (m *MockOfflineCacheStore) WriteBlob(r io.Reader, maxBytes int64) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WriteBlob", r, maxBytes)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// WriteBlob indicates an expected call of WriteBlob.
func (mr *MockOfflineCacheStoreMockRecorder) WriteBlob(r, maxBytes interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WriteBlob", reflect.TypeOf((*MockOfflineCacheStore)(nil).WriteBlob), r, maxBytes)
}
