// Code generated by MockGen. DO NOT EDIT.
// Source: staticserver.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	http "net/http"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockOfflineCacheStaticServer is a mock of StaticServer interface.
type MockOfflineCacheStaticServer struct {
	ctrl     *gomock.Controller
	recorder *MockOfflineCacheStaticServerMockRecorder
}

// MockOfflineCacheStaticServerMockRecorder is the mock recorder for MockOfflineCacheStaticServer.
type MockOfflineCacheStaticServerMockRecorder struct {
	mock *MockOfflineCacheStaticServer
}

// NewMockOfflineCacheStaticServer creates a new mock instance.
func NewMockOfflineCacheStaticServer(ctrl *gomock.Controller) *MockOfflineCacheStaticServer {
	mock := &MockOfflineCacheStaticServer{ctrl: ctrl}
	mock.recorder = &MockOfflineCacheStaticServerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockOfflineCacheStaticServer) EXPECT() *MockOfflineCacheStaticServerMockRecorder {
	return m.recorder
}

// BaseURL mocks base method.
func (m *MockOfflineCacheStaticServer) BaseURL() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BaseURL")
	ret0, _ := ret[0].(string)
	return ret0
}

// BaseURL indicates an expected call of BaseURL.
func (mr *MockOfflineCacheStaticServerMockRecorder) BaseURL() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BaseURL", reflect.TypeOf((*MockOfflineCacheStaticServer)(nil).BaseURL))
}

// Handler mocks base method.
func (m *MockOfflineCacheStaticServer) Handler() http.Handler {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Handler")
	ret0, _ := ret[0].(http.Handler)
	return ret0
}

// Handler indicates an expected call of Handler.
func (mr *MockOfflineCacheStaticServerMockRecorder) Handler() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Handler", reflect.TypeOf((*MockOfflineCacheStaticServer)(nil).Handler))
}

// ListenAndServe mocks base method.
func (m *MockOfflineCacheStaticServer) ListenAndServe() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListenAndServe")
	ret0, _ := ret[0].(error)
	return ret0
}

// ListenAndServe indicates an expected call of ListenAndServe.
func (mr *MockOfflineCacheStaticServerMockRecorder) ListenAndServe() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListenAndServe", reflect.TypeOf((*MockOfflineCacheStaticServer)(nil).ListenAndServe))
}

// Shutdown mocks base method.
func (m *MockOfflineCacheStaticServer) Shutdown(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Shutdown", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// Shutdown indicates an expected call of Shutdown.
func (mr *MockOfflineCacheStaticServerMockRecorder) Shutdown(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Shutdown", reflect.TypeOf((*MockOfflineCacheStaticServer)(nil).Shutdown), ctx)
}

// URLFor mocks base method.
func (m *MockOfflineCacheStaticServer) URLFor(sha256Hex, contentType string) string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "URLFor", sha256Hex, contentType)
	ret0, _ := ret[0].(string)
	return ret0
}

// URLFor indicates an expected call of URLFor.
func (mr *MockOfflineCacheStaticServerMockRecorder) URLFor(sha256Hex, contentType interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "URLFor", reflect.TypeOf((*MockOfflineCacheStaticServer)(nil).URLFor), sha256Hex, contentType)
}
