// Code generated by MockGen. DO NOT EDIT.
// Source: replay.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	offlinecache "github.com/feral-file/ffos-user/components/feral-controld/offlinecache"
	gomock "github.com/golang/mock/gomock"
)

// MockOfflineCacheReplayer is a mock of Replayer interface.
type MockOfflineCacheReplayer struct {
	ctrl     *gomock.Controller
	recorder *MockOfflineCacheReplayerMockRecorder
}

// MockOfflineCacheReplayerMockRecorder is the mock recorder for MockOfflineCacheReplayer.
type MockOfflineCacheReplayerMockRecorder struct {
	mock *MockOfflineCacheReplayer
}

// NewMockOfflineCacheReplayer creates a new mock instance.
func NewMockOfflineCacheReplayer(ctrl *gomock.Controller) *MockOfflineCacheReplayer {
	mock := &MockOfflineCacheReplayer{ctrl: ctrl}
	mock.recorder = &MockOfflineCacheReplayerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockOfflineCacheReplayer) EXPECT() *MockOfflineCacheReplayerMockRecorder {
	return m.recorder
}

// Attach mocks base method.
func (m *MockOfflineCacheReplayer) Attach(sessionID string, session offlinecache.CDPSession) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Attach", sessionID, session)
}

// Attach indicates an expected call of Attach.
func (mr *MockOfflineCacheReplayerMockRecorder) Attach(sessionID, session interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Attach", reflect.TypeOf((*MockOfflineCacheReplayer)(nil).Attach), sessionID, session)
}

// AttachChild mocks base method.
func (m *MockOfflineCacheReplayer) AttachChild(root offlinecache.CDPSession, sessionID string, session offlinecache.CDPSession) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AttachChild", root, sessionID, session)
	ret0, _ := ret[0].(bool)
	return ret0
}

// AttachChild indicates an expected call of AttachChild.
func (mr *MockOfflineCacheReplayerMockRecorder) AttachChild(root, sessionID, session interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AttachChild", reflect.TypeOf((*MockOfflineCacheReplayer)(nil).AttachChild), root, sessionID, session)
}

// Detach mocks base method.
func (m *MockOfflineCacheReplayer) Detach(sessionID string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Detach", sessionID)
}

// Detach indicates an expected call of Detach.
func (mr *MockOfflineCacheReplayerMockRecorder) Detach(sessionID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Detach", reflect.TypeOf((*MockOfflineCacheReplayer)(nil).Detach), sessionID)
}

// DetachChild mocks base method.
func (m *MockOfflineCacheReplayer) DetachChild(root offlinecache.CDPSession, sessionID string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "DetachChild", root, sessionID)
}

// DetachChild indicates an expected call of DetachChild.
func (mr *MockOfflineCacheReplayerMockRecorder) DetachChild(root, sessionID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DetachChild", reflect.TypeOf((*MockOfflineCacheReplayer)(nil).DetachChild), root, sessionID)
}

// Disable mocks base method.
func (m *MockOfflineCacheReplayer) Disable(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Disable", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// Disable indicates an expected call of Disable.
func (mr *MockOfflineCacheReplayerMockRecorder) Disable(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Disable", reflect.TypeOf((*MockOfflineCacheReplayer)(nil).Disable), ctx)
}

// EnableForItem mocks base method.
func (m *MockOfflineCacheReplayer) EnableForItem(ctx context.Context, source string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "EnableForItem", ctx, source)
	ret0, _ := ret[0].(error)
	return ret0
}

// EnableForItem indicates an expected call of EnableForItem.
func (mr *MockOfflineCacheReplayerMockRecorder) EnableForItem(ctx, source interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EnableForItem", reflect.TypeOf((*MockOfflineCacheReplayer)(nil).EnableForItem), ctx, source)
}

// EnableForPlaylist mocks base method.
func (m *MockOfflineCacheReplayer) EnableForPlaylist(ctx context.Context, sources []string, mixed bool) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "EnableForPlaylist", ctx, sources, mixed)
	ret0, _ := ret[0].(error)
	return ret0
}

// EnableForPlaylist indicates an expected call of EnableForPlaylist.
func (mr *MockOfflineCacheReplayerMockRecorder) EnableForPlaylist(ctx, sources, mixed interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EnableForPlaylist", reflect.TypeOf((*MockOfflineCacheReplayer)(nil).EnableForPlaylist), ctx, sources, mixed)
}

// RootAttached mocks base method.
func (m *MockOfflineCacheReplayer) RootAttached() bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RootAttached")
	ret0, _ := ret[0].(bool)
	return ret0
}

// RootAttached indicates an expected call of RootAttached.
func (mr *MockOfflineCacheReplayerMockRecorder) RootAttached() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RootAttached", reflect.TypeOf((*MockOfflineCacheReplayer)(nil).RootAttached))
}

// MockScopeLostRegistrar is a mock of ScopeLostRegistrar interface.
type MockScopeLostRegistrar struct {
	ctrl     *gomock.Controller
	recorder *MockScopeLostRegistrarMockRecorder
}

// MockScopeLostRegistrarMockRecorder is the mock recorder for MockScopeLostRegistrar.
type MockScopeLostRegistrarMockRecorder struct {
	mock *MockScopeLostRegistrar
}

// NewMockScopeLostRegistrar creates a new mock instance.
func NewMockScopeLostRegistrar(ctrl *gomock.Controller) *MockScopeLostRegistrar {
	mock := &MockScopeLostRegistrar{ctrl: ctrl}
	mock.recorder = &MockScopeLostRegistrarMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockScopeLostRegistrar) EXPECT() *MockScopeLostRegistrarMockRecorder {
	return m.recorder
}

// SetOnScopeLost mocks base method.
func (m *MockScopeLostRegistrar) SetOnScopeLost(fn func()) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetOnScopeLost", fn)
}

// SetOnScopeLost indicates an expected call of SetOnScopeLost.
func (mr *MockScopeLostRegistrarMockRecorder) SetOnScopeLost(fn interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetOnScopeLost", reflect.TypeOf((*MockScopeLostRegistrar)(nil).SetOnScopeLost), fn)
}
