// Code generated by MockGen. DO NOT EDIT.
// Source: downloader.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockOfflineCacheDownloader is a mock of Downloader interface.
type MockOfflineCacheDownloader struct {
	ctrl     *gomock.Controller
	recorder *MockOfflineCacheDownloaderMockRecorder
}

// MockOfflineCacheDownloaderMockRecorder is the mock recorder for MockOfflineCacheDownloader.
type MockOfflineCacheDownloaderMockRecorder struct {
	mock *MockOfflineCacheDownloader
}

// NewMockOfflineCacheDownloader creates a new mock instance.
func NewMockOfflineCacheDownloader(ctrl *gomock.Controller) *MockOfflineCacheDownloader {
	mock := &MockOfflineCacheDownloader{ctrl: ctrl}
	mock.recorder = &MockOfflineCacheDownloaderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockOfflineCacheDownloader) EXPECT() *MockOfflineCacheDownloaderMockRecorder {
	return m.recorder
}

// Acquire mocks base method.
func (m *MockOfflineCacheDownloader) Acquire(ctx context.Context) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Acquire", ctx)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Acquire indicates an expected call of Acquire.
func (mr *MockOfflineCacheDownloaderMockRecorder) Acquire(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Acquire", reflect.TypeOf((*MockOfflineCacheDownloader)(nil).Acquire), ctx)
}

// Close mocks base method.
func (m *MockOfflineCacheDownloader) Close() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Close")
	ret0, _ := ret[0].(error)
	return ret0
}

// Close indicates an expected call of Close.
func (mr *MockOfflineCacheDownloaderMockRecorder) Close() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockOfflineCacheDownloader)(nil).Close))
}

// Release mocks base method.
func (m *MockOfflineCacheDownloader) Release() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Release")
}

// Release indicates an expected call of Release.
func (mr *MockOfflineCacheDownloaderMockRecorder) Release() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Release", reflect.TypeOf((*MockOfflineCacheDownloader)(nil).Release))
}
