// Code generated by MockGen. DO NOT EDIT.
// Source: mediacapture.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	playlist "github.com/display-protocol/dp1-go/playlist"
	offlinecache "github.com/feral-file/ffos-user/components/feral-controld/offlinecache"
	gomock "github.com/golang/mock/gomock"
)

// MockOfflineCacheMediaCapturer is a mock of MediaCapturer interface.
type MockOfflineCacheMediaCapturer struct {
	ctrl     *gomock.Controller
	recorder *MockOfflineCacheMediaCapturerMockRecorder
}

// MockOfflineCacheMediaCapturerMockRecorder is the mock recorder for MockOfflineCacheMediaCapturer.
type MockOfflineCacheMediaCapturerMockRecorder struct {
	mock *MockOfflineCacheMediaCapturer
}

// NewMockOfflineCacheMediaCapturer creates a new mock instance.
func NewMockOfflineCacheMediaCapturer(ctrl *gomock.Controller) *MockOfflineCacheMediaCapturer {
	mock := &MockOfflineCacheMediaCapturer{ctrl: ctrl}
	mock.recorder = &MockOfflineCacheMediaCapturerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockOfflineCacheMediaCapturer) EXPECT() *MockOfflineCacheMediaCapturerMockRecorder {
	return m.recorder
}

// Capture mocks base method.
func (m *MockOfflineCacheMediaCapturer) Capture(ctx context.Context, item playlist.PlaylistItem) (*offlinecache.ItemRecord, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Capture", ctx, item)
	ret0, _ := ret[0].(*offlinecache.ItemRecord)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Capture indicates an expected call of Capture.
func (mr *MockOfflineCacheMediaCapturerMockRecorder) Capture(ctx, item interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Capture", reflect.TypeOf((*MockOfflineCacheMediaCapturer)(nil).Capture), ctx, item)
}
