// Code generated by MockGen. DO NOT EDIT.
// Source: recoverer.go
//
// Generated by this command:
//
//	mockgen -source=recoverer.go -destination=../mocks/oom_recoverer.go -package=mocks -mock_names=Recoverer=MockOOMRecoverer
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockOOMRecoverer is a mock of Recoverer interface.
type MockOOMRecoverer struct {
	ctrl     *gomock.Controller
	recorder *MockOOMRecovererMockRecorder
	isgomock struct{}
}

// MockOOMRecovererMockRecorder is the mock recorder for MockOOMRecoverer.
type MockOOMRecovererMockRecorder struct {
	mock *MockOOMRecoverer
}

// NewMockOOMRecoverer creates a new mock instance.
func NewMockOOMRecoverer(ctrl *gomock.Controller) *MockOOMRecoverer {
	mock := &MockOOMRecoverer{ctrl: ctrl}
	mock.recorder = &MockOOMRecovererMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockOOMRecoverer) EXPECT() *MockOOMRecovererMockRecorder {
	return m.recorder
}

// Start mocks base method.
func (m *MockOOMRecoverer) Start(ctx context.Context) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Start", ctx)
}

// Start indicates an expected call of Start.
func (mr *MockOOMRecovererMockRecorder) Start(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Start", reflect.TypeOf((*MockOOMRecoverer)(nil).Start), ctx)
}
