// Code generated by MockGen. DO NOT EDIT.
// Source: scheduler.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	dp1 "github.com/feral-file/ffos-user/components/feral-controld/dp1"
	playlistschedule "github.com/feral-file/ffos-user/components/feral-controld/playlistschedule"
	gomock "github.com/golang/mock/gomock"
)

// MockPlaylistScheduler is a mock of Scheduler interface.
type MockPlaylistScheduler struct {
	ctrl     *gomock.Controller
	recorder *MockPlaylistSchedulerMockRecorder
}

// MockPlaylistSchedulerMockRecorder is the mock recorder for MockPlaylistScheduler.
type MockPlaylistSchedulerMockRecorder struct {
	mock *MockPlaylistScheduler
}

// NewMockPlaylistScheduler creates a new mock instance.
func NewMockPlaylistScheduler(ctrl *gomock.Controller) *MockPlaylistScheduler {
	mock := &MockPlaylistScheduler{ctrl: ctrl}
	mock.recorder = &MockPlaylistSchedulerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPlaylistScheduler) EXPECT() *MockPlaylistSchedulerMockRecorder {
	return m.recorder
}

// AuthorityToken mocks base method.
func (m *MockPlaylistScheduler) AuthorityToken() uint64 {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AuthorityToken")
	ret0, _ := ret[0].(uint64)
	return ret0
}

// AuthorityToken indicates an expected call of AuthorityToken.
func (mr *MockPlaylistSchedulerMockRecorder) AuthorityToken() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AuthorityToken", reflect.TypeOf((*MockPlaylistScheduler)(nil).AuthorityToken))
}

// Clear mocks base method.
func (m *MockPlaylistScheduler) Clear() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Clear")
}

// Clear indicates an expected call of Clear.
func (mr *MockPlaylistSchedulerMockRecorder) Clear() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Clear", reflect.TypeOf((*MockPlaylistScheduler)(nil).Clear))
}

// ClearThenWithPlayerPush mocks base method.
func (m *MockPlaylistScheduler) ClearThenWithPlayerPush(fn func() bool) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "ClearThenWithPlayerPush", fn)
}

// ClearThenWithPlayerPush indicates an expected call of ClearThenWithPlayerPush.
func (mr *MockPlaylistSchedulerMockRecorder) ClearThenWithPlayerPush(fn interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ClearThenWithPlayerPush", reflect.TypeOf((*MockPlaylistScheduler)(nil).ClearThenWithPlayerPush), fn)
}

// Commit mocks base method.
func (m *MockPlaylistScheduler) Commit() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Commit")
}

// Commit indicates an expected call of Commit.
func (mr *MockPlaylistSchedulerMockRecorder) Commit() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Commit", reflect.TypeOf((*MockPlaylistScheduler)(nil).Commit))
}

// HasCache mocks base method.
func (m *MockPlaylistScheduler) HasCache() bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HasCache")
	ret0, _ := ret[0].(bool)
	return ret0
}

// HasCache indicates an expected call of HasCache.
func (mr *MockPlaylistSchedulerMockRecorder) HasCache() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HasCache", reflect.TypeOf((*MockPlaylistScheduler)(nil).HasCache))
}

// Prepare mocks base method.
func (m *MockPlaylistScheduler) Prepare(playlist *dp1.Playlist) *dp1.Playlist {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Prepare", playlist)
	ret0, _ := ret[0].(*dp1.Playlist)
	return ret0
}

// Prepare indicates an expected call of Prepare.
func (mr *MockPlaylistSchedulerMockRecorder) Prepare(playlist interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Prepare", reflect.TypeOf((*MockPlaylistScheduler)(nil).Prepare), playlist)
}

// PrepareWithSource mocks base method.
func (m *MockPlaylistScheduler) PrepareWithSource(playlist *dp1.Playlist, source playlistschedule.Source) *dp1.Playlist {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PrepareWithSource", playlist, source)
	ret0, _ := ret[0].(*dp1.Playlist)
	return ret0
}

// PrepareWithSource indicates an expected call of PrepareWithSource.
func (mr *MockPlaylistSchedulerMockRecorder) PrepareWithSource(playlist, source interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PrepareWithSource", reflect.TypeOf((*MockPlaylistScheduler)(nil).PrepareWithSource), playlist, source)
}

// RecomputeNow mocks base method.
func (m *MockPlaylistScheduler) RecomputeNow(ctx context.Context) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "RecomputeNow", ctx)
}

// RecomputeNow indicates an expected call of RecomputeNow.
func (mr *MockPlaylistSchedulerMockRecorder) RecomputeNow(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RecomputeNow", reflect.TypeOf((*MockPlaylistScheduler)(nil).RecomputeNow), ctx)
}

// Restore mocks base method.
func (m *MockPlaylistScheduler) Restore(arg0 playlistschedule.Snapshot) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Restore", arg0)
}

// Restore indicates an expected call of Restore.
func (mr *MockPlaylistSchedulerMockRecorder) Restore(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Restore", reflect.TypeOf((*MockPlaylistScheduler)(nil).Restore), arg0)
}

// RestoredPending mocks base method.
func (m *MockPlaylistScheduler) RestoredPending() bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RestoredPending")
	ret0, _ := ret[0].(bool)
	return ret0
}

// RestoredPending indicates an expected call of RestoredPending.
func (mr *MockPlaylistSchedulerMockRecorder) RestoredPending() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RestoredPending", reflect.TypeOf((*MockPlaylistScheduler)(nil).RestoredPending))
}

// ResumePersisted mocks base method.
func (m *MockPlaylistScheduler) ResumePersisted(ctx context.Context) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "ResumePersisted", ctx)
}

// ResumePersisted indicates an expected call of ResumePersisted.
func (mr *MockPlaylistSchedulerMockRecorder) ResumePersisted(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ResumePersisted", reflect.TypeOf((*MockPlaylistScheduler)(nil).ResumePersisted), ctx)
}

// SetPushObserver mocks base method.
func (m *MockPlaylistScheduler) SetPushObserver(fn func(playlistschedule.PushPhase)) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetPushObserver", fn)
}

// SetPushObserver indicates an expected call of SetPushObserver.
func (mr *MockPlaylistSchedulerMockRecorder) SetPushObserver(fn interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetPushObserver", reflect.TypeOf((*MockPlaylistScheduler)(nil).SetPushObserver), fn)
}

// Snapshot mocks base method.
func (m *MockPlaylistScheduler) Snapshot() playlistschedule.Snapshot {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Snapshot")
	ret0, _ := ret[0].(playlistschedule.Snapshot)
	return ret0
}

// Snapshot indicates an expected call of Snapshot.
func (mr *MockPlaylistSchedulerMockRecorder) Snapshot() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Snapshot", reflect.TypeOf((*MockPlaylistScheduler)(nil).Snapshot))
}

// Source mocks base method.
func (m *MockPlaylistScheduler) Source() playlistschedule.Source {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Source")
	ret0, _ := ret[0].(playlistschedule.Source)
	return ret0
}

// Source indicates an expected call of Source.
func (mr *MockPlaylistSchedulerMockRecorder) Source() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Source", reflect.TypeOf((*MockPlaylistScheduler)(nil).Source))
}

// SourceMatches mocks base method.
func (m *MockPlaylistScheduler) SourceMatches(source playlistschedule.Source) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SourceMatches", source)
	ret0, _ := ret[0].(bool)
	return ret0
}

// SourceMatches indicates an expected call of SourceMatches.
func (mr *MockPlaylistSchedulerMockRecorder) SourceMatches(source interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SourceMatches", reflect.TypeOf((*MockPlaylistScheduler)(nil).SourceMatches), source)
}

// Stop mocks base method.
func (m *MockPlaylistScheduler) Stop() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Stop")
}

// Stop indicates an expected call of Stop.
func (mr *MockPlaylistSchedulerMockRecorder) Stop() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Stop", reflect.TypeOf((*MockPlaylistScheduler)(nil).Stop))
}

// WithPlayerPush mocks base method.
func (m *MockPlaylistScheduler) WithPlayerPush(fn func()) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "WithPlayerPush", fn)
}

// WithPlayerPush indicates an expected call of WithPlayerPush.
func (mr *MockPlaylistSchedulerMockRecorder) WithPlayerPush(fn interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WithPlayerPush", reflect.TypeOf((*MockPlaylistScheduler)(nil).WithPlayerPush), fn)
}
