// Code generated by MockGen. DO NOT EDIT.
// Source: status.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	status "github.com/feral-file/ffos-user/components/feral-controld/status"
	gomock "github.com/golang/mock/gomock"
)

// MockStatusPoller is a mock of Poller interface.
type MockStatusPoller struct {
	ctrl     *gomock.Controller
	recorder *MockStatusPollerMockRecorder
}

// MockStatusPollerMockRecorder is the mock recorder for MockStatusPoller.
type MockStatusPollerMockRecorder struct {
	mock *MockStatusPoller
}

// NewMockStatusPoller creates a new mock instance.
func NewMockStatusPoller(ctrl *gomock.Controller) *MockStatusPoller {
	mock := &MockStatusPoller{ctrl: ctrl}
	mock.recorder = &MockStatusPollerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStatusPoller) EXPECT() *MockStatusPollerMockRecorder {
	return m.recorder
}

// FetchPlayerStatus mocks base method.
func (m *MockStatusPoller) FetchPlayerStatus(ctx context.Context) (*status.PlayerStatus, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FetchPlayerStatus", ctx)
	ret0, _ := ret[0].(*status.PlayerStatus)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FetchPlayerStatus indicates an expected call of FetchPlayerStatus.
func (mr *MockStatusPollerMockRecorder) FetchPlayerStatus(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FetchPlayerStatus", reflect.TypeOf((*MockStatusPoller)(nil).FetchPlayerStatus), ctx)
}

// ForceRefresh mocks base method.
func (m *MockStatusPoller) ForceRefresh() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "ForceRefresh")
}

// ForceRefresh indicates an expected call of ForceRefresh.
func (mr *MockStatusPollerMockRecorder) ForceRefresh() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ForceRefresh", reflect.TypeOf((*MockStatusPoller)(nil).ForceRefresh))
}

// Start mocks base method.
func (m *MockStatusPoller) Start(ctx context.Context) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Start", ctx)
}

// Start indicates an expected call of Start.
func (mr *MockStatusPollerMockRecorder) Start(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Start", reflect.TypeOf((*MockStatusPoller)(nil).Start), ctx)
}

// Stop mocks base method.
func (m *MockStatusPoller) Stop() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Stop")
}

// Stop indicates an expected call of Stop.
func (mr *MockStatusPollerMockRecorder) Stop() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Stop", reflect.TypeOf((*MockStatusPoller)(nil).Stop))
}
