// Code generated by MockGen. DO NOT EDIT.
// Source: ws.go
//
// Generated by this command:
//
//	mockgen -source=ws.go -destination=../mocks/ws.go -package=mocks -mock_names=WS=MockWS
//

// Package mocks is a generated GoMock package.
package mocks

import (
	http "net/http"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockWS is a mock of WS interface.
type MockWS struct {
	ctrl     *gomock.Controller
	recorder *MockWSMockRecorder
	isgomock struct{}
}

// MockWSMockRecorder is the mock recorder for MockWS.
type MockWSMockRecorder struct {
	mock *MockWS
}

// NewMockWS creates a new mock instance.
func NewMockWS(ctrl *gomock.Controller) *MockWS {
	mock := &MockWS{ctrl: ctrl}
	mock.recorder = &MockWSMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockWS) EXPECT() *MockWSMockRecorder {
	return m.recorder
}

// Close mocks base method.
func (m *MockWS) Close() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Close")
}

// Close indicates an expected call of Close.
func (mr *MockWSMockRecorder) Close() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockWS)(nil).Close))
}

// NewConnection mocks base method.
func (m *MockWS) NewConnection(w http.ResponseWriter, r *http.Request) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NewConnection", w, r)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// NewConnection indicates an expected call of NewConnection.
func (mr *MockWSMockRecorder) NewConnection(w, r any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NewConnection", reflect.TypeOf((*MockWS)(nil).NewConnection), w, r)
}

// Send mocks base method.
func (m *MockWS) Send(connID string, message any) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Send", connID, message)
	ret0, _ := ret[0].(error)
	return ret0
}

// Send indicates an expected call of Send.
func (mr *MockWSMockRecorder) Send(connID, message any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Send", reflect.TypeOf((*MockWS)(nil).Send), connID, message)
}

// SendAll mocks base method.
func (m *MockWS) SendAll(message any) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendAll", message)
	ret0, _ := ret[0].(error)
	return ret0
}

// SendAll indicates an expected call of SendAll.
func (mr *MockWSMockRecorder) SendAll(message any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendAll", reflect.TypeOf((*MockWS)(nil).SendAll), message)
}
