// Code generated by MockGen. DO NOT EDIT.
// Source: json.go

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockJSON is a mock of JSON interface.
type MockJSON struct {
	ctrl     *gomock.Controller
	recorder *MockJSONMockRecorder
}

// MockJSONMockRecorder is the mock recorder for MockJSON.
type MockJSONMockRecorder struct {
	mock *MockJSON
}

// NewMockJSON creates a new mock instance.
func NewMockJSON(ctrl *gomock.Controller) *MockJSON {
	mock := &MockJSON{ctrl: ctrl}
	mock.recorder = &MockJSONMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockJSON) EXPECT() *MockJSONMockRecorder {
	return m.recorder
}

// Marshal mocks base method.
func (m *MockJSON) Marshal(v interface{}) ([]byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Marshal", v)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Marshal indicates an expected call of Marshal.
func (mr *MockJSONMockRecorder) Marshal(v interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Marshal", reflect.TypeOf((*MockJSON)(nil).Marshal), v)
}

// Unmarshal mocks base method.
func (m *MockJSON) Unmarshal(data []byte, v interface{}) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Unmarshal", data, v)
	ret0, _ := ret[0].(error)
	return ret0
}

// Unmarshal indicates an expected call of Unmarshal.
func (mr *MockJSONMockRecorder) Unmarshal(data, v interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Unmarshal", reflect.TypeOf((*MockJSON)(nil).Unmarshal), data, v)
}
