// Code generated by MockGen. DO NOT EDIT.
// Source: relayer.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	relayer "github.com/Feral-File/feralfile-device/components/feral-connectd/relayer"
	gomock "github.com/golang/mock/gomock"
)

// MockRelayer is a mock of Relayer interface.
type MockRelayer struct {
	ctrl     *gomock.Controller
	recorder *MockRelayerMockRecorder
}

// MockRelayerMockRecorder is the mock recorder for MockRelayer.
type MockRelayerMockRecorder struct {
	mock *MockRelayer
}

// NewMockRelayer creates a new mock instance.
func NewMockRelayer(ctrl *gomock.Controller) *MockRelayer {
	mock := &MockRelayer{ctrl: ctrl}
	mock.recorder = &MockRelayerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRelayer) EXPECT() *MockRelayerMockRecorder {
	return m.recorder
}

// Close mocks base method.
func (m *MockRelayer) Close() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Close")
}

// Close indicates an expected call of Close.
func (mr *MockRelayerMockRecorder) Close() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockRelayer)(nil).Close))
}

// Connect mocks base method.
func (m *MockRelayer) Connect(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Connect", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// Connect indicates an expected call of Connect.
func (mr *MockRelayerMockRecorder) Connect(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Connect", reflect.TypeOf((*MockRelayer)(nil).Connect), ctx)
}

// IsConnected mocks base method.
func (m *MockRelayer) IsConnected() bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsConnected")
	ret0, _ := ret[0].(bool)
	return ret0
}

// IsConnected indicates an expected call of IsConnected.
func (mr *MockRelayerMockRecorder) IsConnected() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsConnected", reflect.TypeOf((*MockRelayer)(nil).IsConnected))
}

// OnRelayerMessage mocks base method.
func (m *MockRelayer) OnRelayerMessage(handler relayer.Handler) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "OnRelayerMessage", handler)
}

// OnRelayerMessage indicates an expected call of OnRelayerMessage.
func (mr *MockRelayerMockRecorder) OnRelayerMessage(handler interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "OnRelayerMessage", reflect.TypeOf((*MockRelayer)(nil).OnRelayerMessage), handler)
}

// RemoveRelayerMessage mocks base method.
func (m *MockRelayer) RemoveRelayerMessage(handler relayer.Handler) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "RemoveRelayerMessage", handler)
}

// RemoveRelayerMessage indicates an expected call of RemoveRelayerMessage.
func (mr *MockRelayerMockRecorder) RemoveRelayerMessage(handler interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveRelayerMessage", reflect.TypeOf((*MockRelayer)(nil).RemoveRelayerMessage), handler)
}

// RetryableConnect mocks base method.
func (m *MockRelayer) RetryableConnect(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RetryableConnect", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// RetryableConnect indicates an expected call of RetryableConnect.
func (mr *MockRelayerMockRecorder) RetryableConnect(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RetryableConnect", reflect.TypeOf((*MockRelayer)(nil).RetryableConnect), ctx)
}

// Send mocks base method.
func (m *MockRelayer) Send(ctx context.Context, data interface{}) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Send", ctx, data)
	ret0, _ := ret[0].(error)
	return ret0
}

// Send indicates an expected call of Send.
func (mr *MockRelayerMockRecorder) Send(ctx, data interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Send", reflect.TypeOf((*MockRelayer)(nil).Send), ctx, data)
}

// SendNotification mocks base method.
func (m *MockRelayer) SendNotification(ctx context.Context, notificationType relayer.NotificationType, message interface{}) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendNotification", ctx, notificationType, message)
	ret0, _ := ret[0].(error)
	return ret0
}

// SendNotification indicates an expected call of SendNotification.
func (mr *MockRelayerMockRecorder) SendNotification(ctx, notificationType, message interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendNotification", reflect.TypeOf((*MockRelayer)(nil).SendNotification), ctx, notificationType, message)
}
