// Code generated by MockGen. DO NOT EDIT.
// Source: cdp.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockCDP is a mock of CDP interface.
type MockCDP struct {
	ctrl     *gomock.Controller
	recorder *MockCDPMockRecorder
}

// MockCDPMockRecorder is the mock recorder for MockCDP.
type MockCDPMockRecorder struct {
	mock *MockCDP
}

// NewMockCDP creates a new mock instance.
func NewMockCDP(ctrl *gomock.Controller) *MockCDP {
	mock := &MockCDP{ctrl: ctrl}
	mock.recorder = &MockCDPMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCDP) EXPECT() *MockCDPMockRecorder {
	return m.recorder
}

// Close mocks base method.
func (m *MockCDP) Close() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Close")
}

// Close indicates an expected call of Close.
func (mr *MockCDPMockRecorder) Close() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockCDP)(nil).Close))
}

// Init mocks base method.
func (m *MockCDP) Init(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Init", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// Init indicates an expected call of Init.
func (mr *MockCDPMockRecorder) Init(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Init", reflect.TypeOf((*MockCDP)(nil).Init), ctx)
}

// Initialized mocks base method.
func (m *MockCDP) Initialized() bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Initialized")
	ret0, _ := ret[0].(bool)
	return ret0
}

// Initialized indicates an expected call of Initialized.
func (mr *MockCDPMockRecorder) Initialized() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Initialized", reflect.TypeOf((*MockCDP)(nil).Initialized))
}

// ShowCriticalTemperature mocks base method.
func (m *MockCDP) ShowCriticalTemperature(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ShowCriticalTemperature", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// ShowCriticalTemperature indicates an expected call of ShowCriticalTemperature.
func (mr *MockCDPMockRecorder) ShowCriticalTemperature(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ShowCriticalTemperature", reflect.TypeOf((*MockCDP)(nil).ShowCriticalTemperature), ctx)
}

// ShowServiceFailedToStart mocks base method.
func (m *MockCDP) ShowServiceFailedToStart(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ShowServiceFailedToStart", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// ShowServiceFailedToStart indicates an expected call of ShowServiceFailedToStart.
func (mr *MockCDPMockRecorder) ShowServiceFailedToStart(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ShowServiceFailedToStart", reflect.TypeOf((*MockCDP)(nil).ShowServiceFailedToStart), ctx)
}
