// Code generated by MockGen. DO NOT EDIT.
// Source: chromium.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockChromiumMonitor is a mock of ChromiumMonitor interface.
type MockChromiumMonitor struct {
	ctrl     *gomock.Controller
	recorder *MockChromiumMonitorMockRecorder
}

// MockChromiumMonitorMockRecorder is the mock recorder for MockChromiumMonitor.
type MockChromiumMonitorMockRecorder struct {
	mock *MockChromiumMonitor
}

// NewMockChromiumMonitor creates a new mock instance.
func NewMockChromiumMonitor(ctrl *gomock.Controller) *MockChromiumMonitor {
	mock := &MockChromiumMonitor{ctrl: ctrl}
	mock.recorder = &MockChromiumMonitorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockChromiumMonitor) EXPECT() *MockChromiumMonitorMockRecorder {
	return m.recorder
}

// Start mocks base method.
func (m *MockChromiumMonitor) Start(ctx context.Context) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Start", ctx)
}

// Start indicates an expected call of Start.
func (mr *MockChromiumMonitorMockRecorder) Start(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Start", reflect.TypeOf((*MockChromiumMonitor)(nil).Start), ctx)
}

// Stop mocks base method.
func (m *MockChromiumMonitor) Stop() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Stop")
}

// Stop indicates an expected call of Stop.
func (mr *MockChromiumMonitorMockRecorder) Stop() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Stop", reflect.TypeOf((*MockChromiumMonitor)(nil).Stop))
}
