// Code generated by MockGen. DO NOT EDIT.
// Source: cpu.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockCPUHandler is a mock of CPUHandler interface.
type MockCPUHandler struct {
	ctrl     *gomock.Controller
	recorder *MockCPUHandlerMockRecorder
}

// MockCPUHandlerMockRecorder is the mock recorder for MockCPUHandler.
type MockCPUHandlerMockRecorder struct {
	mock *MockCPUHandler
}

// NewMockCPUHandler creates a new mock instance.
func NewMockCPUHandler(ctrl *gomock.Controller) *MockCPUHandler {
	mock := &MockCPUHandler{ctrl: ctrl}
	mock.recorder = &MockCPUHandlerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCPUHandler) EXPECT() *MockCPUHandlerMockRecorder {
	return m.recorder
}

// HandleTemperature mocks base method.
func (m *MockCPUHandler) HandleTemperature(ctx context.Context, temperature float64) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "HandleTemperature", ctx, temperature)
}

// HandleTemperature indicates an expected call of HandleTemperature.
func (mr *MockCPUHandlerMockRecorder) HandleTemperature(ctx, temperature interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HandleTemperature", reflect.TypeOf((*MockCPUHandler)(nil).HandleTemperature), ctx, temperature)
}
