// Code generated by MockGen. DO NOT EDIT.
// Source: daemon.go

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockDaemon is a mock of Daemon interface.
type MockDaemon struct {
	ctrl     *gomock.Controller
	recorder *MockDaemonMockRecorder
}

// MockDaemonMockRecorder is the mock recorder for MockDaemon.
type MockDaemonMockRecorder struct {
	mock *MockDaemon
}

// NewMockDaemon creates a new mock instance.
func NewMockDaemon(ctrl *gomock.Controller) *MockDaemon {
	mock := &MockDaemon{ctrl: ctrl}
	mock.recorder = &MockDaemonMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDaemon) EXPECT() *MockDaemonMockRecorder {
	return m.recorder
}

// SdNotify mocks base method.
func (m *MockDaemon) SdNotify(unsetEnvironment bool, state string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SdNotify", unsetEnvironment, state)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SdNotify indicates an expected call of SdNotify.
func (mr *MockDaemonMockRecorder) SdNotify(unsetEnvironment, state interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SdNotify", reflect.TypeOf((*MockDaemon)(nil).SdNotify), unsetEnvironment, state)
}
