// Code generated by MockGen. DO NOT EDIT.
// Source: disk.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockDiskHandler is a mock of DiskHandler interface.
type MockDiskHandler struct {
	ctrl     *gomock.Controller
	recorder *MockDiskHandlerMockRecorder
}

// MockDiskHandlerMockRecorder is the mock recorder for MockDiskHandler.
type MockDiskHandlerMockRecorder struct {
	mock *MockDiskHandler
}

// NewMockDiskHandler creates a new mock instance.
func NewMockDiskHandler(ctrl *gomock.Controller) *MockDiskHandler {
	mock := &MockDiskHandler{ctrl: ctrl}
	mock.recorder = &MockDiskHandlerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDiskHandler) EXPECT() *MockDiskHandlerMockRecorder {
	return m.recorder
}

// HandleUsage mocks base method.
func (m *MockDiskHandler) HandleUsage(ctx context.Context, usagePercent float64) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "HandleUsage", ctx, usagePercent)
}

// HandleUsage indicates an expected call of HandleUsage.
func (mr *MockDiskHandlerMockRecorder) HandleUsage(ctx, usagePercent interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HandleUsage", reflect.TypeOf((*MockDiskHandler)(nil).HandleUsage), ctx, usagePercent)
}
