// Code generated by MockGen. DO NOT EDIT.
// Source: executor.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"

	command "github.com/feral-file/ffos-user/components/feral-watchdog/command"
	vmagent "github.com/feral-file/ffos-user/components/feral-watchdog/vmagent"
)

// MockCommandExecutor is a mock of Executor interface.
type MockCommandExecutor struct {
	ctrl     *gomock.Controller
	recorder *MockCommandExecutorMockRecorder
}

// MockCommandExecutorMockRecorder is the mock recorder for MockCommandExecutor.
type MockCommandExecutorMockRecorder struct {
	mock *MockCommandExecutor
}

// NewMockCommandExecutor creates a new mock instance.
func NewMockCommandExecutor(ctrl *gomock.Controller) *MockCommandExecutor {
	mock := &MockCommandExecutor{ctrl: ctrl}
	mock.recorder = &MockCommandExecutorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCommandExecutor) EXPECT() *MockCommandExecutorMockRecorder {
	return m.recorder
}

// CheckSystemdUserServiceStatus mocks base method.
func (m *MockCommandExecutor) CheckSystemdUserServiceStatus(ctx context.Context, serviceName string) (*command.SystemdServiceStatus, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckSystemdUserServiceStatus", ctx, serviceName)
	ret0, _ := ret[0].(*command.SystemdServiceStatus)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CheckSystemdUserServiceStatus indicates an expected call of CheckSystemdUserServiceStatus.
func (mr *MockCommandExecutorMockRecorder) CheckSystemdUserServiceStatus(ctx, serviceName interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckSystemdUserServiceStatus", reflect.TypeOf((*MockCommandExecutor)(nil).CheckSystemdUserServiceStatus), ctx, serviceName)
}

// CleanupPacmanCache mocks base method.
func (m *MockCommandExecutor) CleanupPacmanCache(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CleanupPacmanCache", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// CleanupPacmanCache indicates an expected call of CleanupPacmanCache.
func (mr *MockCommandExecutorMockRecorder) CleanupPacmanCache(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CleanupPacmanCache", reflect.TypeOf((*MockCommandExecutor)(nil).CleanupPacmanCache), ctx)
}

// RebootSystem mocks base method.
func (m *MockCommandExecutor) RebootSystem(ctx context.Context, reason vmagent.CrashReason) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RebootSystem", ctx, reason)
	ret0, _ := ret[0].(error)
	return ret0
}

// RebootSystem indicates an expected call of RebootSystem.
func (mr *MockCommandExecutorMockRecorder) RebootSystem(ctx, reason interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RebootSystem", reflect.TypeOf((*MockCommandExecutor)(nil).RebootSystem), ctx, reason)
}

// RestartKiosk mocks base method.
func (m *MockCommandExecutor) RestartKiosk(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RestartKiosk", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// RestartKiosk indicates an expected call of RestartKiosk.
func (mr *MockCommandExecutorMockRecorder) RestartKiosk(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RestartKiosk", reflect.TypeOf((*MockCommandExecutor)(nil).RestartKiosk), ctx)
}
