// Code generated by MockGen. DO NOT EDIT.
// Source: gpu.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockGPUHandler is a mock of GPUHandler interface.
type MockGPUHandler struct {
	ctrl     *gomock.Controller
	recorder *MockGPUHandlerMockRecorder
}

// MockGPUHandlerMockRecorder is the mock recorder for MockGPUHandler.
type MockGPUHandlerMockRecorder struct {
	mock *MockGPUHandler
}

// NewMockGPUHandler creates a new mock instance.
func NewMockGPUHandler(ctrl *gomock.Controller) *MockGPUHandler {
	mock := &MockGPUHandler{ctrl: ctrl}
	mock.recorder = &MockGPUHandlerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGPUHandler) EXPECT() *MockGPUHandlerMockRecorder {
	return m.recorder
}

// CancelScheduledReboot mocks base method.
func (m *MockGPUHandler) CancelScheduledReboot() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "CancelScheduledReboot")
}

// CancelScheduledReboot indicates an expected call of CancelScheduledReboot.
func (mr *MockGPUHandlerMockRecorder) CancelScheduledReboot() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CancelScheduledReboot", reflect.TypeOf((*MockGPUHandler)(nil).CancelScheduledReboot))
}

// HandleEvent mocks base method.
func (m *MockGPUHandler) HandleEvent(ctx context.Context, event string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "HandleEvent", ctx, event)
}

// HandleEvent indicates an expected call of HandleEvent.
func (mr *MockGPUHandlerMockRecorder) HandleEvent(ctx, event interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HandleEvent", reflect.TypeOf((*MockGPUHandler)(nil).HandleEvent), ctx, event)
}
