// Code generated by MockGen. DO NOT EDIT.
// Source: memory.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockMemoryHandler is a mock of MemoryHandler interface.
type MockMemoryHandler struct {
	ctrl     *gomock.Controller
	recorder *MockMemoryHandlerMockRecorder
}

// MockMemoryHandlerMockRecorder is the mock recorder for MockMemoryHandler.
type MockMemoryHandlerMockRecorder struct {
	mock *MockMemoryHandler
}

// NewMockMemoryHandler creates a new mock instance.
func NewMockMemoryHandler(ctrl *gomock.Controller) *MockMemoryHandler {
	mock := &MockMemoryHandler{ctrl: ctrl}
	mock.recorder = &MockMemoryHandlerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMemoryHandler) EXPECT() *MockMemoryHandlerMockRecorder {
	return m.recorder
}

// HandleUsage mocks base method.
func (m *MockMemoryHandler) HandleUsage(ctx context.Context, usagePercent float64) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "HandleUsage", ctx, usagePercent)
}

// HandleUsage indicates an expected call of HandleUsage.
func (mr *MockMemoryHandlerMockRecorder) HandleUsage(ctx, usagePercent interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HandleUsage", reflect.TypeOf((*MockMemoryHandler)(nil).HandleUsage), ctx, usagePercent)
}
