// Code generated by MockGen. DO NOT EDIT.
// Source: systemd.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockSystemdMonitor is a mock of SystemdMonitor interface.
type MockSystemdMonitor struct {
	ctrl     *gomock.Controller
	recorder *MockSystemdMonitorMockRecorder
}

// MockSystemdMonitorMockRecorder is the mock recorder for MockSystemdMonitor.
type MockSystemdMonitorMockRecorder struct {
	mock *MockSystemdMonitor
}

// NewMockSystemdMonitor creates a new mock instance.
func NewMockSystemdMonitor(ctrl *gomock.Controller) *MockSystemdMonitor {
	mock := &MockSystemdMonitor{ctrl: ctrl}
	mock.recorder = &MockSystemdMonitorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSystemdMonitor) EXPECT() *MockSystemdMonitorMockRecorder {
	return m.recorder
}

// Start mocks base method.
func (m *MockSystemdMonitor) Start(ctx context.Context) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Start", ctx)
}

// Start indicates an expected call of Start.
func (mr *MockSystemdMonitorMockRecorder) Start(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Start", reflect.TypeOf((*MockSystemdMonitor)(nil).Start), ctx)
}

// Stop mocks base method.
func (m *MockSystemdMonitor) Stop() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Stop")
}

// Stop indicates an expected call of Stop.
func (mr *MockSystemdMonitorMockRecorder) Stop() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Stop", reflect.TypeOf((*MockSystemdMonitor)(nil).Stop))
}
