// Code generated by MockGen. DO NOT EDIT.
// Source: watcher.go

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockEventWatcher is a mock of Watcher interface.
type MockEventWatcher struct {
	ctrl     *gomock.Controller
	recorder *MockEventWatcherMockRecorder
}

// MockEventWatcherMockRecorder is the mock recorder for MockEventWatcher.
type MockEventWatcherMockRecorder struct {
	mock *MockEventWatcher
}

// NewMockEventWatcher creates a new mock instance.
func NewMockEventWatcher(ctrl *gomock.Controller) *MockEventWatcher {
	mock := &MockEventWatcher{ctrl: ctrl}
	mock.recorder = &MockEventWatcherMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockEventWatcher) EXPECT() *MockEventWatcherMockRecorder {
	return m.recorder
}

// Start mocks base method.
func (m *MockEventWatcher) Start() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Start")
}

// Start indicates an expected call of Start.
func (mr *MockEventWatcherMockRecorder) Start() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Start", reflect.TypeOf((*MockEventWatcher)(nil).Start))
}

// Stop mocks base method.
func (m *MockEventWatcher) Stop() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Stop")
}

// Stop indicates an expected call of Stop.
func (mr *MockEventWatcherMockRecorder) Stop() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Stop", reflect.TypeOf((*MockEventWatcher)(nil).Stop))
}
