// Code generated by MockGen. DO NOT EDIT.
// Source: logger/logger.go

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"
	time "time"

	logger "github.com/feral-file/ffos-user/components/feral-app-monitord/logger"
	gomock "github.com/golang/mock/gomock"
	zap "go.uber.org/zap"
)

// MockLoggerManager is a mock of LoggerManager interface.
type MockLoggerManager struct {
	ctrl     *gomock.Controller
	recorder *MockLoggerManagerMockRecorder
}

// MockLoggerManagerMockRecorder is the mock recorder for MockLoggerManager.
type MockLoggerManagerMockRecorder struct {
	mock *MockLoggerManager
}

// NewMockLoggerManager creates a new mock instance.
func NewMockLoggerManager(ctrl *gomock.Controller) *MockLoggerManager {
	mock := &MockLoggerManager{ctrl: ctrl}
	mock.recorder = &MockLoggerManagerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockLoggerManager) EXPECT() *MockLoggerManagerMockRecorder {
	return m.recorder
}

// FlushSentry mocks base method.
func (m *MockLoggerManager) FlushSentry(timeout time.Duration) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "FlushSentry", timeout)
}

// FlushSentry indicates an expected call of FlushSentry.
func (mr *MockLoggerManagerMockRecorder) FlushSentry(timeout interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FlushSentry", reflect.TypeOf((*MockLoggerManager)(nil).FlushSentry), timeout)
}

// InitSentry mocks base method.
func (m *MockLoggerManager) InitSentry(sentryConfig *logger.SentryConfig) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InitSentry", sentryConfig)
	ret0, _ := ret[0].(error)
	return ret0
}

// InitSentry indicates an expected call of InitSentry.
func (mr *MockLoggerManagerMockRecorder) InitSentry(sentryConfig interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InitSentry", reflect.TypeOf((*MockLoggerManager)(nil).InitSentry), sentryConfig)
}

// New mocks base method.
func (m *MockLoggerManager) New(debug bool) (*zap.Logger, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "New", debug)
	ret0, _ := ret[0].(*zap.Logger)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// New indicates an expected call of New.
func (mr *MockLoggerManagerMockRecorder) New(debug interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "New", reflect.TypeOf((*MockLoggerManager)(nil).New), debug)
}

// NewDefault mocks base method.
func (m *MockLoggerManager) NewDefault() (*zap.Logger, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NewDefault")
	ret0, _ := ret[0].(*zap.Logger)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// NewDefault indicates an expected call of NewDefault.
func (mr *MockLoggerManagerMockRecorder) NewDefault() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NewDefault", reflect.TypeOf((*MockLoggerManager)(nil).NewDefault))
}

// NewWithSentry mocks base method.
func (m *MockLoggerManager) NewWithSentry(debug bool, sentryConfig *logger.SentryConfig) (*zap.Logger, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NewWithSentry", debug, sentryConfig)
	ret0, _ := ret[0].(*zap.Logger)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// NewWithSentry indicates an expected call of NewWithSentry.
func (mr *MockLoggerManagerMockRecorder) NewWithSentry(debug, sentryConfig interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NewWithSentry", reflect.TypeOf((*MockLoggerManager)(nil).NewWithSentry), debug, sentryConfig)
}

// SetGlobalTag mocks base method.
func (m *MockLoggerManager) SetGlobalTag(key, value string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetGlobalTag", key, value)
}

// SetGlobalTag indicates an expected call of SetGlobalTag.
func (mr *MockLoggerManagerMockRecorder) SetGlobalTag(key, value interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetGlobalTag", reflect.TypeOf((*MockLoggerManager)(nil).SetGlobalTag), key, value)
}
