// Code generated by MockGen. DO NOT EDIT.
// Source: handler.go

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"
	time "time"

	gomock "github.com/golang/mock/gomock"

	connectivity "github.com/feral-file/ffos-user/components/feral-sys-monitord/connectivity"
)

// MockConnectivityHandler is a mock of Handler interface.
type MockConnectivityHandler struct {
	ctrl     *gomock.Controller
	recorder *MockConnectivityHandlerMockRecorder
}

// MockConnectivityHandlerMockRecorder is the mock recorder for MockConnectivityHandler.
type MockConnectivityHandlerMockRecorder struct {
	mock *MockConnectivityHandler
}

// NewMockConnectivityHandler creates a new mock instance.
func NewMockConnectivityHandler(ctrl *gomock.Controller) *MockConnectivityHandler {
	mock := &MockConnectivityHandler{ctrl: ctrl}
	mock.recorder = &MockConnectivityHandlerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockConnectivityHandler) EXPECT() *MockConnectivityHandlerMockRecorder {
	return m.recorder
}

// AddHandler mocks base method.
func (m *MockConnectivityHandler) AddHandler(f connectivity.HandlerFunc) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "AddHandler", f)
}

// AddHandler indicates an expected call of AddHandler.
func (mr *MockConnectivityHandlerMockRecorder) AddHandler(f interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddHandler", reflect.TypeOf((*MockConnectivityHandler)(nil).AddHandler), f)
}

// CheckConnectivity mocks base method.
func (m *MockConnectivityHandler) CheckConnectivity(timeout time.Duration) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckConnectivity", timeout)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CheckConnectivity indicates an expected call of CheckConnectivity.
func (mr *MockConnectivityHandlerMockRecorder) CheckConnectivity(timeout interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckConnectivity", reflect.TypeOf((*MockConnectivityHandler)(nil).CheckConnectivity), timeout)
}

// GetLastConnected mocks base method.
func (m *MockConnectivityHandler) GetLastConnected() bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLastConnected")
	ret0, _ := ret[0].(bool)
	return ret0
}

// GetLastConnected indicates an expected call of GetLastConnected.
func (mr *MockConnectivityHandlerMockRecorder) GetLastConnected() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLastConnected", reflect.TypeOf((*MockConnectivityHandler)(nil).GetLastConnected))
}

// RemoveHandler mocks base method.
func (m *MockConnectivityHandler) RemoveHandler(f connectivity.HandlerFunc) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "RemoveHandler", f)
}

// RemoveHandler indicates an expected call of RemoveHandler.
func (mr *MockConnectivityHandlerMockRecorder) RemoveHandler(f interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveHandler", reflect.TypeOf((*MockConnectivityHandler)(nil).RemoveHandler), f)
}

// Start mocks base method.
func (m *MockConnectivityHandler) Start() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Start")
}

// Start indicates an expected call of Start.
func (mr *MockConnectivityHandlerMockRecorder) Start() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Start", reflect.TypeOf((*MockConnectivityHandler)(nil).Start))
}

// Stop mocks base method.
func (m *MockConnectivityHandler) Stop() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Stop")
}

// Stop indicates an expected call of Stop.
func (mr *MockConnectivityHandlerMockRecorder) Stop() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Stop", reflect.TypeOf((*MockConnectivityHandler)(nil).Stop))
}
