// Code generated by MockGen. DO NOT EDIT.
// Source: filepath.go

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockFilepath is a mock of Filepath interface.
type MockFilepath struct {
	ctrl     *gomock.Controller
	recorder *MockFilepathMockRecorder
}

// MockFilepathMockRecorder is the mock recorder for MockFilepath.
type MockFilepathMockRecorder struct {
	mock *MockFilepath
}

// NewMockFilepath creates a new mock instance.
func NewMockFilepath(ctrl *gomock.Controller) *MockFilepath {
	mock := &MockFilepath{ctrl: ctrl}
	mock.recorder = &MockFilepathMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockFilepath) EXPECT() *MockFilepathMockRecorder {
	return m.recorder
}

// Glob mocks base method.
func (m *MockFilepath) Glob(pattern string) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Glob", pattern)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Glob indicates an expected call of Glob.
func (mr *MockFilepathMockRecorder) Glob(pattern interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Glob", reflect.TypeOf((*MockFilepath)(nil).Glob), pattern)
}
