// Code generated by MockGen. DO NOT EDIT.
// Source: monitor.go

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"

	metric "github.com/feral-file/ffos-user/components/feral-sys-monitord/metric"
)

// MockMonitor is a mock of Monitor interface.
type MockMonitor struct {
	ctrl     *gomock.Controller
	recorder *MockMonitorMockRecorder
}

// MockMonitorMockRecorder is the mock recorder for MockMonitor.
type MockMonitorMockRecorder struct {
	mock *MockMonitor
}

// NewMockMonitor creates a new mock instance.
func NewMockMonitor(ctrl *gomock.Controller) *MockMonitor {
	mock := &MockMonitor{ctrl: ctrl}
	mock.recorder = &MockMonitorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMonitor) EXPECT() *MockMonitorMockRecorder {
	return m.recorder
}

// AddHandler mocks base method.
func (m *MockMonitor) AddHandler(f metric.HandlerFunc) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "AddHandler", f)
}

// AddHandler indicates an expected call of AddHandler.
func (mr *MockMonitorMockRecorder) AddHandler(f interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddHandler", reflect.TypeOf((*MockMonitor)(nil).AddHandler), f)
}

// LastMetrics mocks base method.
func (m *MockMonitor) LastMetrics() *metric.SystemMetrics {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LastMetrics")
	ret0, _ := ret[0].(*metric.SystemMetrics)
	return ret0
}

// LastMetrics indicates an expected call of LastMetrics.
func (mr *MockMonitorMockRecorder) LastMetrics() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LastMetrics", reflect.TypeOf((*MockMonitor)(nil).LastMetrics))
}

// RemoveHandler mocks base method.
func (m *MockMonitor) RemoveHandler(f metric.HandlerFunc) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "RemoveHandler", f)
}

// RemoveHandler indicates an expected call of RemoveHandler.
func (mr *MockMonitorMockRecorder) RemoveHandler(f interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveHandler", reflect.TypeOf((*MockMonitor)(nil).RemoveHandler), f)
}

// Start mocks base method.
func (m *MockMonitor) Start() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Start")
}

// Start indicates an expected call of Start.
func (mr *MockMonitorMockRecorder) Start() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Start", reflect.TypeOf((*MockMonitor)(nil).Start))
}

// Stop mocks base method.
func (m *MockMonitor) Stop() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Stop")
}

// Stop indicates an expected call of Stop.
func (mr *MockMonitorMockRecorder) Stop() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Stop", reflect.TypeOf((*MockMonitor)(nil).Stop))
}
