// Code generated by MockGen. DO NOT EDIT.
// Source: strconv.go

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockStrconv is a mock of Strconv interface.
type MockStrconv struct {
	ctrl     *gomock.Controller
	recorder *MockStrconvMockRecorder
}

// MockStrconvMockRecorder is the mock recorder for MockStrconv.
type MockStrconvMockRecorder struct {
	mock *MockStrconv
}

// NewMockStrconv creates a new mock instance.
func NewMockStrconv(ctrl *gomock.Controller) *MockStrconv {
	mock := &MockStrconv{ctrl: ctrl}
	mock.recorder = &MockStrconvMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStrconv) EXPECT() *MockStrconvMockRecorder {
	return m.recorder
}

// Atoi mocks base method.
func (m *MockStrconv) Atoi(s string) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Atoi", s)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Atoi indicates an expected call of Atoi.
func (mr *MockStrconvMockRecorder) Atoi(s interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Atoi", reflect.TypeOf((*MockStrconv)(nil).Atoi), s)
}

// ParseFloat mocks base method.
func (m *MockStrconv) ParseFloat(s string, bitSize int) (float64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ParseFloat", s, bitSize)
	ret0, _ := ret[0].(float64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ParseFloat indicates an expected call of ParseFloat.
func (mr *MockStrconvMockRecorder) ParseFloat(s, bitSize interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ParseFloat", reflect.TypeOf((*MockStrconv)(nil).ParseFloat), s, bitSize)
}

// ParseInt mocks base method.
func (m *MockStrconv) ParseInt(s string, base, bitSize int) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ParseInt", s, base, bitSize)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ParseInt indicates an expected call of ParseInt.
func (mr *MockStrconvMockRecorder) ParseInt(s, base, bitSize interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ParseInt", reflect.TypeOf((*MockStrconv)(nil).ParseInt), s, base, bitSize)
}
