// Code generated by MockGen. DO NOT EDIT.
// Source: watcher.go

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"

	event "github.com/feral-file/ffos-user/components/feral-sys-monitord/event"
)

// MockWatcher is a mock of Watcher interface.
type MockWatcher struct {
	ctrl     *gomock.Controller
	recorder *MockWatcherMockRecorder
}

// MockWatcherMockRecorder is the mock recorder for MockWatcher.
type MockWatcherMockRecorder struct {
	mock *MockWatcher
}

// NewMockWatcher creates a new mock instance.
func NewMockWatcher(ctrl *gomock.Controller) *MockWatcher {
	mock := &MockWatcher{ctrl: ctrl}
	mock.recorder = &MockWatcherMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockWatcher) EXPECT() *MockWatcherMockRecorder {
	return m.recorder
}

// AddHandler mocks base method.
func (m *MockWatcher) AddHandler(f event.HandlerFunc) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "AddHandler", f)
}

// AddHandler indicates an expected call of AddHandler.
func (mr *MockWatcherMockRecorder) AddHandler(f interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddHandler", reflect.TypeOf((*MockWatcher)(nil).AddHandler), f)
}

// RemoveHandler mocks base method.
func (m *MockWatcher) RemoveHandler(f event.HandlerFunc) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "RemoveHandler", f)
}

// RemoveHandler indicates an expected call of RemoveHandler.
func (mr *MockWatcherMockRecorder) RemoveHandler(f interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveHandler", reflect.TypeOf((*MockWatcher)(nil).RemoveHandler), f)
}

// Start mocks base method.
func (m *MockWatcher) Start() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Start")
}

// Start indicates an expected call of Start.
func (mr *MockWatcherMockRecorder) Start() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Start", reflect.TypeOf((*MockWatcher)(nil).Start))
}

// Stop mocks base method.
func (m *MockWatcher) Stop() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Stop")
}

// Stop indicates an expected call of Stop.
func (mr *MockWatcherMockRecorder) Stop() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Stop", reflect.TypeOf((*MockWatcher)(nil).Stop))
}
