name: Testing

on:
  push:
    branches: [main, develop]

jobs:
  test-controld:
    name: Test Controld
    uses: ./.github/workflows/test-controld.yaml
    with:
      upload-coverage: true
    secrets: inherit

  test-setupd:
    name: Test Setupd
    uses: ./.github/workflows/test-setupd.yaml
    with:
      upload-coverage: true
    secrets: inherit

  test-sys-monitord:
    name: Test Sys Monitord
    uses: ./.github/workflows/test-sys-monitord.yaml
    with:
      upload-coverage: true
    secrets: inherit

  test-watchdog:
    name: Test Watchdog
    uses: ./.github/workflows/test-watchdog.yaml
    with:
      upload-coverage: true
    secrets: inherit
